// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/callerauth/v1/callerauth.proto

package callerauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallerAuthCode int32

const (
	CallerAuthCode_CALLER_AUTH_CODE_UNSPECIFIED CallerAuthCode = 0
	// Delegate resolved the token; caller_id is the identity.
	CallerAuthCode_CALLER_AUTH_CODE_OK CallerAuthCode = 1
	// Delegate explicitly rejected the token (revoked / unknown).
	// Surfaces as anonymous today; 401 once enforce mode ships.
	CallerAuthCode_CALLER_AUTH_CODE_DENIED CallerAuthCode = 2
	// Delegate is currently unavailable (degraded backend, exceeded
	// budget, etc.). Caller resolves to anonymous; no cache write.
	CallerAuthCode_CALLER_AUTH_CODE_UNAVAILABLE CallerAuthCode = 3
	// Delegate is registered but unwilling to make a decision (e.g.
	// policy not loaded). Same surface as UNAVAILABLE.
	CallerAuthCode_CALLER_AUTH_CODE_NOT_CONFIGURED CallerAuthCode = 4
)

// Enum value maps for CallerAuthCode.
var (
	CallerAuthCode_name = map[int32]string{
		0: "CALLER_AUTH_CODE_UNSPECIFIED",
		1: "CALLER_AUTH_CODE_OK",
		2: "CALLER_AUTH_CODE_DENIED",
		3: "CALLER_AUTH_CODE_UNAVAILABLE",
		4: "CALLER_AUTH_CODE_NOT_CONFIGURED",
	}
	CallerAuthCode_value = map[string]int32{
		"CALLER_AUTH_CODE_UNSPECIFIED":    0,
		"CALLER_AUTH_CODE_OK":             1,
		"CALLER_AUTH_CODE_DENIED":         2,
		"CALLER_AUTH_CODE_UNAVAILABLE":    3,
		"CALLER_AUTH_CODE_NOT_CONFIGURED": 4,
	}
)

func (x CallerAuthCode) Enum() *CallerAuthCode {
	p := new(CallerAuthCode)
	*p = x
	return p
}

func (x CallerAuthCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallerAuthCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_proto_callerauth_v1_callerauth_proto_enumTypes[0].Descriptor()
}

func (CallerAuthCode) Type() protoreflect.EnumType {
	return &file_gw_proto_callerauth_v1_callerauth_proto_enumTypes[0]
}

func (x CallerAuthCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallerAuthCode.Descriptor instead.
func (CallerAuthCode) EnumDescriptor() ([]byte, []int) {
	return file_gw_proto_callerauth_v1_callerauth_proto_rawDescGZIP(), []int{0}
}

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque token presented by the client. Empty string when the
	// inbound request had no caller-token — the delegate decides
	// whether to map it to a known anonymous identity.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Inbound remote address (best-effort; may be empty if the gateway
	// is behind a proxy that doesn't forward it).
	RemoteAddr    string `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_gw_proto_callerauth_v1_callerauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_callerauth_v1_callerauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_callerauth_v1_callerauth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthorizeRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  CallerAuthCode         `protobuf:"varint,1,opt,name=code,proto3,enum=gateway.callerauth.v1.CallerAuthCode" json:"code,omitempty"`
	// Resolved caller identity. Required when code == OK; ignored
	// otherwise.
	CallerId string `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// Override the configured cache TTL for this specific token.
	// Zero = use the configured default. Capped at the configured
	// maximum so a misbehaving delegate can't pin a stale identity
	// forever.
	TtlSeconds uint32 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Optional, for operator logs. Never leaked to clients.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_gw_proto_callerauth_v1_callerauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_callerauth_v1_callerauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_gw_proto_callerauth_v1_callerauth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetCode() CallerAuthCode {
	if x != nil {
		return x.Code
	}
	return CallerAuthCode_CALLER_AUTH_CODE_UNSPECIFIED
}

func (x *AuthorizeResponse) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *AuthorizeResponse) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TokenRevoked is the NATS event body published on
// "events.caller_auth.Revoked" to invalidate a single token entry
// across every gateway in the cluster.
type TokenRevoked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRevoked) Reset() {
	*x = TokenRevoked{}
	mi := &file_gw_proto_callerauth_v1_callerauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevoked) ProtoMessage() {}

func (x *TokenRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_callerauth_v1_callerauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevoked.ProtoReflect.Descriptor instead.
func (*TokenRevoked) Descriptor() ([]byte, []int) {
	return file_gw_proto_callerauth_v1_callerauth_proto_rawDescGZIP(), []int{2}
}

func (x *TokenRevoked) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_gw_proto_callerauth_v1_callerauth_proto protoreflect.FileDescriptor

const file_gw_proto_callerauth_v1_callerauth_proto_rawDesc = "" +
	"\n" +
	"'gw/proto/callerauth/v1/callerauth.proto\x12\x15gateway.callerauth.v1\"I\n" +
	"\x10AuthorizeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vremote_addr\x18\x02 \x01(\tR\n" +
	"remoteAddr\"\xa4\x01\n" +
	"\x11AuthorizeResponse\x129\n" +
	"\x04code\x18\x01 \x01(\x0e2%.gateway.callerauth.v1.CallerAuthCodeR\x04code\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"$\n" +
	"\fTokenRevoked\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token*\xaf\x01\n" +
	"\x0eCallerAuthCode\x12 \n" +
	"\x1cCALLER_AUTH_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CALLER_AUTH_CODE_OK\x10\x01\x12\x1b\n" +
	"\x17CALLER_AUTH_CODE_DENIED\x10\x02\x12 \n" +
	"\x1cCALLER_AUTH_CODE_UNAVAILABLE\x10\x03\x12#\n" +
	"\x1fCALLER_AUTH_CODE_NOT_CONFIGURED\x10\x042r\n" +
	"\x10CallerAuthorizer\x12^\n" +
	"\tAuthorize\x12'.gateway.callerauth.v1.AuthorizeRequest\x1a(.gateway.callerauth.v1.AuthorizeResponseBKZIgithub.com/iodesystems/go-api-gateway/gw/proto/callerauth/v1;callerauthv1b\x06proto3"

var (
	file_gw_proto_callerauth_v1_callerauth_proto_rawDescOnce sync.Once
	file_gw_proto_callerauth_v1_callerauth_proto_rawDescData []byte
)

func file_gw_proto_callerauth_v1_callerauth_proto_rawDescGZIP() []byte {
	file_gw_proto_callerauth_v1_callerauth_proto_rawDescOnce.Do(func() {
		file_gw_proto_callerauth_v1_callerauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_callerauth_v1_callerauth_proto_rawDesc), len(file_gw_proto_callerauth_v1_callerauth_proto_rawDesc)))
	})
	return file_gw_proto_callerauth_v1_callerauth_proto_rawDescData
}

var file_gw_proto_callerauth_v1_callerauth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gw_proto_callerauth_v1_callerauth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gw_proto_callerauth_v1_callerauth_proto_goTypes = []any{
	(CallerAuthCode)(0),       // 0: gateway.callerauth.v1.CallerAuthCode
	(*AuthorizeRequest)(nil),  // 1: gateway.callerauth.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 2: gateway.callerauth.v1.AuthorizeResponse
	(*TokenRevoked)(nil),      // 3: gateway.callerauth.v1.TokenRevoked
}
var file_gw_proto_callerauth_v1_callerauth_proto_depIdxs = []int32{
	0, // 0: gateway.callerauth.v1.AuthorizeResponse.code:type_name -> gateway.callerauth.v1.CallerAuthCode
	1, // 1: gateway.callerauth.v1.CallerAuthorizer.Authorize:input_type -> gateway.callerauth.v1.AuthorizeRequest
	2, // 2: gateway.callerauth.v1.CallerAuthorizer.Authorize:output_type -> gateway.callerauth.v1.AuthorizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gw_proto_callerauth_v1_callerauth_proto_init() }
func file_gw_proto_callerauth_v1_callerauth_proto_init() {
	if File_gw_proto_callerauth_v1_callerauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_callerauth_v1_callerauth_proto_rawDesc), len(file_gw_proto_callerauth_v1_callerauth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_callerauth_v1_callerauth_proto_goTypes,
		DependencyIndexes: file_gw_proto_callerauth_v1_callerauth_proto_depIdxs,
		EnumInfos:         file_gw_proto_callerauth_v1_callerauth_proto_enumTypes,
		MessageInfos:      file_gw_proto_callerauth_v1_callerauth_proto_msgTypes,
	}.Build()
	File_gw_proto_callerauth_v1_callerauth_proto = out.File
	file_gw_proto_callerauth_v1_callerauth_proto_goTypes = nil
	file_gw_proto_callerauth_v1_callerauth_proto_depIdxs = nil
}
