// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gw/proto/callerauth/v1/callerauth.proto

package callerauthv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallerAuthorizer_Authorize_FullMethodName = "/gateway.callerauth.v1.CallerAuthorizer/Authorize"
)

// CallerAuthorizerClient is the client API for CallerAuthorizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CallerAuthorizer is the optional delegate the gateway calls to
// resolve an inbound caller token into a caller-id. Implement it in
// your authz service and register it under namespace "_caller_auth" /
// version v1.
//
// Wire flow: client presents a token (X-Caller-Token HTTP header /
// caller-token gRPC metadata key). The gateway's WithCallerIDDelegated
// extractor calls Authorize(token); on OK the response.caller_id is
// the resolved identity. Token → caller_id mapping is cached locally
// for ttl_seconds (or the option's default if zero) and refreshed via
// singleflight so a burst of concurrent misses collapses to one RPC.
//
// Negative invalidation: publish a CallerRevoked event on
// "events.caller_auth.Revoked" (NATS); listeners drop the matching
// cache entry. The event body is a TokenRevoked message.
//
// Code policy mirrors AdminAuthorizer: OK accepts, DENIED rejects
// (anonymous / 401 surface depending on enforce mode), anything else
// (UNAVAILABLE, NOT_CONFIGURED, UNSPECIFIED, transport error) is
// treated as "no decision today" — the caller resolves to anonymous
// for metrics, and once WithCallerIDEnforce ships those become 401.
type CallerAuthorizerClient interface {
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
}

type callerAuthorizerClient struct {
	cc grpc.ClientConnInterface
}

func NewCallerAuthorizerClient(cc grpc.ClientConnInterface) CallerAuthorizerClient {
	return &callerAuthorizerClient{cc}
}

func (c *callerAuthorizerClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, CallerAuthorizer_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallerAuthorizerServer is the server API for CallerAuthorizer service.
// All implementations must embed UnimplementedCallerAuthorizerServer
// for forward compatibility.
//
// CallerAuthorizer is the optional delegate the gateway calls to
// resolve an inbound caller token into a caller-id. Implement it in
// your authz service and register it under namespace "_caller_auth" /
// version v1.
//
// Wire flow: client presents a token (X-Caller-Token HTTP header /
// caller-token gRPC metadata key). The gateway's WithCallerIDDelegated
// extractor calls Authorize(token); on OK the response.caller_id is
// the resolved identity. Token → caller_id mapping is cached locally
// for ttl_seconds (or the option's default if zero) and refreshed via
// singleflight so a burst of concurrent misses collapses to one RPC.
//
// Negative invalidation: publish a CallerRevoked event on
// "events.caller_auth.Revoked" (NATS); listeners drop the matching
// cache entry. The event body is a TokenRevoked message.
//
// Code policy mirrors AdminAuthorizer: OK accepts, DENIED rejects
// (anonymous / 401 surface depending on enforce mode), anything else
// (UNAVAILABLE, NOT_CONFIGURED, UNSPECIFIED, transport error) is
// treated as "no decision today" — the caller resolves to anonymous
// for metrics, and once WithCallerIDEnforce ships those become 401.
type CallerAuthorizerServer interface {
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	mustEmbedUnimplementedCallerAuthorizerServer()
}

// UnimplementedCallerAuthorizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallerAuthorizerServer struct{}

func (UnimplementedCallerAuthorizerServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedCallerAuthorizerServer) mustEmbedUnimplementedCallerAuthorizerServer() {}
func (UnimplementedCallerAuthorizerServer) testEmbeddedByValue()                          {}

// UnsafeCallerAuthorizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallerAuthorizerServer will
// result in compilation errors.
type UnsafeCallerAuthorizerServer interface {
	mustEmbedUnimplementedCallerAuthorizerServer()
}

func RegisterCallerAuthorizerServer(s grpc.ServiceRegistrar, srv CallerAuthorizerServer) {
	// If the following call panics, it indicates UnimplementedCallerAuthorizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallerAuthorizer_ServiceDesc, srv)
}

func _CallerAuthorizer_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallerAuthorizerServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallerAuthorizer_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallerAuthorizerServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallerAuthorizer_ServiceDesc is the grpc.ServiceDesc for CallerAuthorizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallerAuthorizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.callerauth.v1.CallerAuthorizer",
	HandlerType: (*CallerAuthorizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _CallerAuthorizer_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gw/proto/callerauth/v1/callerauth.proto",
}
