// PLACEHOLDER. Real content is generated by `pnpm run codegen` from
// schema.graphql + src/**/*.graphql. After running codegen, this file
// exports a `getSdk(client)` returning typed query/mutation functions.
// The placeholder lets `tsc` succeed before the first codegen run; do
// not commit edits to this file other than running codegen.

import type { GraphQLClient } from 'graphql-request';

export type Sdk = {
  Dashboard: () => Promise<any>;
  Services: () => Promise<any>;
  Peers: () => Promise<any>;
  ForgetPeer: (vars: { nodeId: string }) => Promise<any>;
};

export function getSdk(_client: GraphQLClient): Sdk {
  const todo = async () => {
    throw new Error('UI codegen has not been run yet. Run `pnpm run gen`.');
  };
  return {
    Dashboard: todo,
    Services: todo,
    Peers: todo,
    ForgetPeer: todo,
  };
}
