// PLACEHOLDER. Real content is generated by `pnpm run codegen` from
// schema.graphql + src/**/*.graphql. After running codegen, this file
// exports a `getSdk(client)` returning typed query/mutation functions.
// The placeholder lets `tsc` succeed before the first codegen run; do
// not commit edits to this file other than running codegen.

import type { GraphQLClient } from 'graphql-request';

// Shape after `pnpm run gen` runs against the gateway's actual SDL.
// admin_* fields are flat because they're huma-generated OpenAPI
// operations ingested into GraphQL (vs proto-style nested namespaces).
//
// The placeholder return types are tight enough that .map((p, i) =>)
// callbacks in the route files don't trip noImplicitAny — peers /
// services are `any[]` rather than `any`. Real codegen-emitted Sdk
// will replace this with proper field types.
export type Sdk = {
  Dashboard: () => Promise<{
    admin_listPeers?: { peers?: any[] };
    admin_listServices?: { services?: any[]; environment?: string };
  }>;
  Services: () => Promise<{
    admin_listServices?: { services?: any[]; environment?: string };
  }>;
  Peers: () => Promise<{
    admin_listPeers?: { peers?: any[] };
  }>;
  ForgetPeer: (vars: { nodeId: string }) => Promise<{
    admin_forgetPeer?: { removed?: boolean };
  }>;
};

export function getSdk(_client: GraphQLClient): Sdk {
  const todo = async () => {
    throw new Error('UI codegen has not been run yet. Run `pnpm run gen`.');
  };
  return {
    Dashboard: todo,
    Services: todo,
    Peers: todo,
    ForgetPeer: todo,
  };
}
