// Code generated by gnat-ws-relay; DO NOT EDIT.
// The live-subscription runtime for the multiplex relay (gw/relay): ONE shared,
// ref-counted WebSocket carries many logical subscriptions keyed by a per-sub id.
// Authorization happened at the mint endpoint (the adopter's authorizer) — here
// we present the signed token and route data frames. Framework-agnostic core
// (subscribeRaw) + an optional React hook (useWs).
import { useEffect, useRef } from 'react'

// SubResponse is the signed capability a mint endpoint returns. TEvent is a
// phantom carrier (erased at runtime) so callers type the handler with no cast.
export type SubResponse<TEvent> = {
  token: string
  channel: string
  exp: string
  readonly __event?: TEvent
}

// relayPath is the WS endpoint the relay is mounted at (same-origin). Override
// with setRelayPath before the first subscription if it differs.
let relayPath = '/ws'
export function setRelayPath(path: string): void {
  relayPath = path
}

type OutFrame = { op: string; id: string; payload?: unknown; err?: string }

// MuxSocket owns the single shared connection. Subs queue until open; the socket
// closes when the last sub goes away and re-opens on the next sub.
class MuxSocket {
  private ws: WebSocket | null = null
  private handlers = new Map<string, (e: unknown) => void>()
  private pending: string[] = []
  private seq = 0
  private refs = 0

  private url(): string {
    const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
    return `${proto}//${window.location.host}${relayPath}`
  }

  private connect(): void {
    if (this.ws) return
    const ws = new WebSocket(this.url())
    this.ws = ws
    ws.onopen = () => {
      for (const f of this.pending) ws.send(f)
      this.pending = []
    }
    ws.onmessage = (ev) => {
      let f: OutFrame
      try {
        f = JSON.parse(ev.data as string) as OutFrame
      } catch {
        return
      }
      if (f.op === 'data') {
        const h = this.handlers.get(f.id)
        if (h) h(f.payload)
      }
    }
    ws.onclose = () => {
      if (this.ws === ws) this.ws = null
    }
  }

  private send(frame: object): void {
    const s = JSON.stringify(frame)
    if (this.ws && this.ws.readyState === WebSocket.OPEN) this.ws.send(s)
    else this.pending.push(s)
  }

  sub(token: string, handler: (e: unknown) => void): () => void {
    this.refs += 1
    this.connect()
    const id = String(++this.seq)
    this.handlers.set(id, handler)
    this.send({ op: 'sub', id, token })
    return () => {
      this.handlers.delete(id)
      this.send({ op: 'unsub', id })
      this.refs -= 1
      if (this.refs <= 0) {
        this.refs = 0
        if (this.ws) this.ws.close()
        this.ws = null
        this.pending = []
      }
    }
  }
}

const mux = new MuxSocket()

// subscribeRaw is the framework-agnostic entry: subscribe to sub's channel,
// routing each event to handler (typed TEvent). Returns an unsubscribe fn.
export function subscribeRaw<TEvent>(
  sub: SubResponse<TEvent>,
  handler: (e: TEvent) => void,
): () => void {
  return mux.sub(sub.token, (e) => handler(e as TEvent))
}

// useWs subscribes to sub's channel for the component's lifetime, routing each
// event to handler with the inferred TEvent type. Pass null to subscribe to
// nothing (e.g. before the mint resolves). Re-subscribes if the token changes.
export function useWs<TEvent>(sub: SubResponse<TEvent> | null, handler: (e: TEvent) => void): void {
  const ref = useRef(handler)
  ref.current = handler
  const token = sub?.token ?? null
  useEffect(() => {
    if (!token || !sub) return
    return subscribeRaw(sub, (e) => ref.current(e))
  }, [token, sub])
}
