// Code generated by gnat-ws-relay; DO NOT EDIT.
// The live-subscription runtime for the multiplex relay (gw/relay): ONE shared,
// ref-counted socket carries many logical subscriptions keyed by a per-sub id.
// The runtime owns the cap lifecycle (connect, reconnect, renew, revalidate); the
// app owns *how to get a cap* — you pass a minter `() => Promise<SubResponse>`,
// the runtime calls it whenever it needs a fresh one. (Same shape as Ably's
// authCallback / Pusher's authorizer.) Framework-agnostic core (subscribeRaw) +
// an optional React hook (useSub).
import { useEffect, useRef } from 'react'

// SubResponse is the signed capability a mint endpoint returns. TEvent is a
// phantom carrier (erased at runtime) so callers type the handler with no cast.
export type SubResponse<TEvent> = {
  token: string
  channel: string
  exp: string
  readonly __event?: TEvent
}

// A Minter produces a fresh capability on demand. Called by the runtime on the
// initial subscribe and again on reconnect / renew / revalidate.
export type Minter<TEvent> = () => Promise<SubResponse<TEvent>>

// relayPath is the WS endpoint the relay is mounted at (same-origin). Override
// with setRelayPath before the first subscription if it differs.
let relayPath = '/ws'
export function setRelayPath(path: string): void {
  relayPath = path
}

type OutFrame = { op: string; id: string; payload?: unknown; err?: string }

// MuxSocket owns the single shared connection and per-sub minters. On (re)connect
// it re-mints every active sub; on a `revalidate` frame it re-mints that one; it
// auto-reconnects with backoff + jitter while any sub remains.
class MuxSocket {
  private ws: WebSocket | null = null
  private mints = new Map<string, Minter<unknown>>()
  private handlers = new Map<string, (e: unknown) => void>()
  private seq = 0
  private attempt = 0
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null

  private url(): string {
    const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
    return `${proto}//${window.location.host}${relayPath}`
  }

  private connect(): void {
    if (this.ws) return
    const ws = new WebSocket(this.url())
    this.ws = ws
    ws.onopen = () => {
      this.attempt = 0
      for (const id of this.mints.keys()) void this.activate(id) // re-mint + re-sub all
    }
    ws.onmessage = (ev) => {
      let f: OutFrame
      try {
        f = JSON.parse(ev.data as string) as OutFrame
      } catch {
        return
      }
      if (f.op === 'data') {
        const h = this.handlers.get(f.id)
        if (h) h(f.payload)
      } else if (f.op === 'revalidate') {
        void this.activate(f.id) // relay asked for a fresh cap on this sub
      }
    }
    ws.onclose = () => {
      if (this.ws === ws) this.ws = null
      if (this.mints.size > 0) this.scheduleReconnect()
    }
  }

  private scheduleReconnect(): void {
    if (this.reconnectTimer) return
    const base = Math.min(10_000, 500 * Math.pow(1.5, this.attempt++))
    const delay = base / 2 + Math.random() * (base / 2) // jitter [base/2, base] — spread reconnect/re-mint storms
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null
      this.connect()
    }, delay)
  }

  private async activate(id: string): Promise<void> {
    const mint = this.mints.get(id)
    if (!mint) return
    let cap: SubResponse<unknown>
    try {
      cap = await mint() // re-runs the app's authorizer (canSee); throws if denied
    } catch {
      return // denied / mint unavailable — drop silently; the app's poll fallback covers it
    }
    if (!this.mints.has(id)) return // unsubscribed while minting
    this.send({ op: 'sub', id, token: cap.token })
  }

  private send(frame: object): void {
    if (this.ws && this.ws.readyState === WebSocket.OPEN) this.ws.send(JSON.stringify(frame))
    // not open → onopen re-activates every sub; a stray unsub for a closed socket is moot
  }

  sub<T>(mint: Minter<T>, handler: (e: T) => void): () => void {
    const id = String(++this.seq)
    this.mints.set(id, mint as Minter<unknown>)
    this.handlers.set(id, handler as (e: unknown) => void)
    if (this.ws && this.ws.readyState === WebSocket.OPEN) void this.activate(id)
    else this.connect()
    return () => {
      this.mints.delete(id)
      this.handlers.delete(id)
      this.send({ op: 'unsub', id })
      if (this.mints.size === 0) {
        if (this.reconnectTimer) {
          clearTimeout(this.reconnectTimer)
          this.reconnectTimer = null
        }
        if (this.ws) this.ws.close()
        this.ws = null
      }
    }
  }
}

const mux = new MuxSocket()

// subscribeRaw is the framework-agnostic entry: subscribe via mint's channel,
// routing each event to handler (typed TEvent). Returns an unsubscribe fn.
export function subscribeRaw<TEvent>(
  mint: Minter<TEvent>,
  handler: (e: TEvent) => void,
): () => void {
  return mux.sub(mint, handler)
}

// useSub subscribes for the component's lifetime. Pass a minter (a thunk that
// mints a fresh cap — the runtime calls it on connect/reconnect/renew/revalidate)
// and a deps array (re-subscribe when these change, like useEffect). TEvent is
// inferred from the minter's return type.
export function useSub<TEvent>(
  mint: Minter<TEvent>,
  handler: (e: TEvent) => void,
  deps: unknown[],
): void {
  const handlerRef = useRef(handler)
  handlerRef.current = handler
  const mintRef = useRef(mint)
  mintRef.current = mint
  useEffect(() => {
    return subscribeRaw(
      () => mintRef.current(),
      (e) => handlerRef.current(e),
    )
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps)
}
