// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/quotaauth/v1/quotaauth.proto

package quotaauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuotaAuthCode int32

const (
	QuotaAuthCode_QUOTA_AUTH_CODE_UNSPECIFIED QuotaAuthCode = 0
	// Delegate granted a block.
	QuotaAuthCode_QUOTA_AUTH_CODE_OK QuotaAuthCode = 1
	// Delegate explicitly refused; caller is over quota. Surfaces as
	// 429 + Retry-After on HTTP/GraphQL, ResourceExhausted on gRPC.
	QuotaAuthCode_QUOTA_AUTH_CODE_DENIED QuotaAuthCode = 2
	// Delegate is currently unavailable. Gateway fails open today.
	QuotaAuthCode_QUOTA_AUTH_CODE_UNAVAILABLE QuotaAuthCode = 3
	// Delegate is registered but unwilling to make a decision (e.g.
	// policy not loaded). Same surface as UNAVAILABLE.
	QuotaAuthCode_QUOTA_AUTH_CODE_NOT_CONFIGURED QuotaAuthCode = 4
)

// Enum value maps for QuotaAuthCode.
var (
	QuotaAuthCode_name = map[int32]string{
		0: "QUOTA_AUTH_CODE_UNSPECIFIED",
		1: "QUOTA_AUTH_CODE_OK",
		2: "QUOTA_AUTH_CODE_DENIED",
		3: "QUOTA_AUTH_CODE_UNAVAILABLE",
		4: "QUOTA_AUTH_CODE_NOT_CONFIGURED",
	}
	QuotaAuthCode_value = map[string]int32{
		"QUOTA_AUTH_CODE_UNSPECIFIED":    0,
		"QUOTA_AUTH_CODE_OK":             1,
		"QUOTA_AUTH_CODE_DENIED":         2,
		"QUOTA_AUTH_CODE_UNAVAILABLE":    3,
		"QUOTA_AUTH_CODE_NOT_CONFIGURED": 4,
	}
)

func (x QuotaAuthCode) Enum() *QuotaAuthCode {
	p := new(QuotaAuthCode)
	*p = x
	return p
}

func (x QuotaAuthCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaAuthCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_proto_quotaauth_v1_quotaauth_proto_enumTypes[0].Descriptor()
}

func (QuotaAuthCode) Type() protoreflect.EnumType {
	return &file_gw_proto_quotaauth_v1_quotaauth_proto_enumTypes[0]
}

func (x QuotaAuthCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuotaAuthCode.Descriptor instead.
func (QuotaAuthCode) EnumDescriptor() ([]byte, []int) {
	return file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescGZIP(), []int{0}
}

type AcquireBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved caller identity (output of the caller-id extractor).
	// "unknown" stands in for anonymous callers; the delegate decides
	// whether to grant anonymous quota.
	CallerId string `protobuf:"bytes,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// The (namespace, version) pair the caller is dispatching against.
	// Lets the delegate apply different quotas per service tier.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version   string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Block size the gateway is asking for, derived from the caller's
	// configured burstable RPS. The delegate may grant fewer.
	RequestedPermits uint32 `protobuf:"varint,4,opt,name=requested_permits,json=requestedPermits,proto3" json:"requested_permits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcquireBlockRequest) Reset() {
	*x = AcquireBlockRequest{}
	mi := &file_gw_proto_quotaauth_v1_quotaauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireBlockRequest) ProtoMessage() {}

func (x *AcquireBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_quotaauth_v1_quotaauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireBlockRequest.ProtoReflect.Descriptor instead.
func (*AcquireBlockRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireBlockRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *AcquireBlockRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AcquireBlockRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AcquireBlockRequest) GetRequestedPermits() uint32 {
	if x != nil {
		return x.RequestedPermits
	}
	return 0
}

type AcquireBlockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  QuotaAuthCode          `protobuf:"varint,1,opt,name=code,proto3,enum=gateway.quotaauth.v1.QuotaAuthCode" json:"code,omitempty"`
	// Number of permits granted. Required when code == OK. Zero with
	// code == OK is treated as DENIED (defensive — a misbehaving
	// delegate shouldn't be able to silently freeze a caller).
	GrantedPermits uint32 `protobuf:"varint,2,opt,name=granted_permits,json=grantedPermits,proto3" json:"granted_permits,omitempty"`
	// Hard deadline after which the granted permits expire regardless
	// of consumption. Empty / zero → permits don't expire on a wall
	// clock; the gateway refills when the bucket drains. Set this to
	// enforce per-second / per-minute caps server-side.
	ValidUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	// Suggested block size for the next AcquireBlock call. Zero → reuse
	// requested_permits. Lets the delegate steer block size based on
	// observed caller behaviour (steady → bigger blocks; bursty → smaller).
	NextBlockHint uint32 `protobuf:"varint,4,opt,name=next_block_hint,json=nextBlockHint,proto3" json:"next_block_hint,omitempty"`
	// For operator logs. Never leaked to clients. Carries the rejection
	// reason for DENIED responses (e.g. "monthly cap exceeded").
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireBlockResponse) Reset() {
	*x = AcquireBlockResponse{}
	mi := &file_gw_proto_quotaauth_v1_quotaauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireBlockResponse) ProtoMessage() {}

func (x *AcquireBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_quotaauth_v1_quotaauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireBlockResponse.ProtoReflect.Descriptor instead.
func (*AcquireBlockResponse) Descriptor() ([]byte, []int) {
	return file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireBlockResponse) GetCode() QuotaAuthCode {
	if x != nil {
		return x.Code
	}
	return QuotaAuthCode_QUOTA_AUTH_CODE_UNSPECIFIED
}

func (x *AcquireBlockResponse) GetGrantedPermits() uint32 {
	if x != nil {
		return x.GrantedPermits
	}
	return 0
}

func (x *AcquireBlockResponse) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *AcquireBlockResponse) GetNextBlockHint() uint32 {
	if x != nil {
		return x.NextBlockHint
	}
	return 0
}

func (x *AcquireBlockResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gw_proto_quotaauth_v1_quotaauth_proto protoreflect.FileDescriptor

const file_gw_proto_quotaauth_v1_quotaauth_proto_rawDesc = "" +
	"\n" +
	"%gw/proto/quotaauth/v1/quotaauth.proto\x12\x14gateway.quotaauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\x13AcquireBlockRequest\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\tR\bcallerId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12+\n" +
	"\x11requested_permits\x18\x04 \x01(\rR\x10requestedPermits\"\xf5\x01\n" +
	"\x14AcquireBlockResponse\x127\n" +
	"\x04code\x18\x01 \x01(\x0e2#.gateway.quotaauth.v1.QuotaAuthCodeR\x04code\x12'\n" +
	"\x0fgranted_permits\x18\x02 \x01(\rR\x0egrantedPermits\x12;\n" +
	"\vvalid_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12&\n" +
	"\x0fnext_block_hint\x18\x04 \x01(\rR\rnextBlockHint\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason*\xa9\x01\n" +
	"\rQuotaAuthCode\x12\x1f\n" +
	"\x1bQUOTA_AUTH_CODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12QUOTA_AUTH_CODE_OK\x10\x01\x12\x1a\n" +
	"\x16QUOTA_AUTH_CODE_DENIED\x10\x02\x12\x1f\n" +
	"\x1bQUOTA_AUTH_CODE_UNAVAILABLE\x10\x03\x12\"\n" +
	"\x1eQUOTA_AUTH_CODE_NOT_CONFIGURED\x10\x042x\n" +
	"\x0fQuotaAuthorizer\x12e\n" +
	"\fAcquireBlock\x12).gateway.quotaauth.v1.AcquireBlockRequest\x1a*.gateway.quotaauth.v1.AcquireBlockResponseB?Z=github.com/iodesystems/gwag/gw/proto/quotaauth/v1;quotaauthv1b\x06proto3"

var (
	file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescOnce sync.Once
	file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescData []byte
)

func file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescGZIP() []byte {
	file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescOnce.Do(func() {
		file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_quotaauth_v1_quotaauth_proto_rawDesc), len(file_gw_proto_quotaauth_v1_quotaauth_proto_rawDesc)))
	})
	return file_gw_proto_quotaauth_v1_quotaauth_proto_rawDescData
}

var file_gw_proto_quotaauth_v1_quotaauth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gw_proto_quotaauth_v1_quotaauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gw_proto_quotaauth_v1_quotaauth_proto_goTypes = []any{
	(QuotaAuthCode)(0),            // 0: gateway.quotaauth.v1.QuotaAuthCode
	(*AcquireBlockRequest)(nil),   // 1: gateway.quotaauth.v1.AcquireBlockRequest
	(*AcquireBlockResponse)(nil),  // 2: gateway.quotaauth.v1.AcquireBlockResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_gw_proto_quotaauth_v1_quotaauth_proto_depIdxs = []int32{
	0, // 0: gateway.quotaauth.v1.AcquireBlockResponse.code:type_name -> gateway.quotaauth.v1.QuotaAuthCode
	3, // 1: gateway.quotaauth.v1.AcquireBlockResponse.valid_until:type_name -> google.protobuf.Timestamp
	1, // 2: gateway.quotaauth.v1.QuotaAuthorizer.AcquireBlock:input_type -> gateway.quotaauth.v1.AcquireBlockRequest
	2, // 3: gateway.quotaauth.v1.QuotaAuthorizer.AcquireBlock:output_type -> gateway.quotaauth.v1.AcquireBlockResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gw_proto_quotaauth_v1_quotaauth_proto_init() }
func file_gw_proto_quotaauth_v1_quotaauth_proto_init() {
	if File_gw_proto_quotaauth_v1_quotaauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_quotaauth_v1_quotaauth_proto_rawDesc), len(file_gw_proto_quotaauth_v1_quotaauth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_quotaauth_v1_quotaauth_proto_goTypes,
		DependencyIndexes: file_gw_proto_quotaauth_v1_quotaauth_proto_depIdxs,
		EnumInfos:         file_gw_proto_quotaauth_v1_quotaauth_proto_enumTypes,
		MessageInfos:      file_gw_proto_quotaauth_v1_quotaauth_proto_msgTypes,
	}.Build()
	File_gw_proto_quotaauth_v1_quotaauth_proto = out.File
	file_gw_proto_quotaauth_v1_quotaauth_proto_goTypes = nil
	file_gw_proto_quotaauth_v1_quotaauth_proto_depIdxs = nil
}
