// PLACEHOLDER. The real content is generated by the
// @tanstack/router-plugin Vite plugin during `pnpm run dev` /
// `pnpm run build` from the route files in src/routes/. The
// placeholder keeps `tsc -b` happy before the plugin has run.
//
// Do not commit edits other than what the plugin produces.

import { createRootRoute } from '@tanstack/react-router';

export const routeTree = createRootRoute();
