/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InjectorsRouteImport } from './routes/injectors'
import { Route as DeprecatedRouteImport } from './routes/deprecated'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InjectorsRoute = InjectorsRouteImport.update({
  id: '/injectors',
  path: '/injectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DeprecatedRoute = DeprecatedRouteImport.update({
  id: '/deprecated',
  path: '/deprecated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deprecated': typeof DeprecatedRoute
  '/injectors': typeof InjectorsRoute
  '/mcp': typeof McpRoute
  '/peers': typeof PeersRoute
  '/schema': typeof SchemaRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deprecated': typeof DeprecatedRoute
  '/injectors': typeof InjectorsRoute
  '/mcp': typeof McpRoute
  '/peers': typeof PeersRoute
  '/schema': typeof SchemaRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deprecated': typeof DeprecatedRoute
  '/injectors': typeof InjectorsRoute
  '/mcp': typeof McpRoute
  '/peers': typeof PeersRoute
  '/schema': typeof SchemaRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deprecated'
    | '/injectors'
    | '/mcp'
    | '/peers'
    | '/schema'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deprecated'
    | '/injectors'
    | '/mcp'
    | '/peers'
    | '/schema'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/deprecated'
    | '/injectors'
    | '/mcp'
    | '/peers'
    | '/schema'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeprecatedRoute: typeof DeprecatedRoute
  InjectorsRoute: typeof InjectorsRoute
  McpRoute: typeof McpRoute
  PeersRoute: typeof PeersRoute
  SchemaRoute: typeof SchemaRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/injectors': {
      id: '/injectors'
      path: '/injectors'
      fullPath: '/injectors'
      preLoaderRoute: typeof InjectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deprecated': {
      id: '/deprecated'
      path: '/deprecated'
      fullPath: '/deprecated'
      preLoaderRoute: typeof DeprecatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeprecatedRoute: DeprecatedRoute,
  InjectorsRoute: InjectorsRoute,
  McpRoute: McpRoute,
  PeersRoute: PeersRoute,
  SchemaRoute: SchemaRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
