// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/eventsauth/v1/eventsauth.proto

package eventsauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeSignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved NATS subject the token will sign.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Wall-clock unix timestamp the gateway is about to embed in the
	// token. Lets the delegate reject tokens that arrive too late
	// relative to its own clock.
	TimestampUnix int64 `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	// Requested validity window for the token. Currently informational;
	// the gateway-side SkewWindow bounds replay regardless.
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeSignRequest) Reset() {
	*x = AuthorizeSignRequest{}
	mi := &file_gw_proto_eventsauth_v1_eventsauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeSignRequest) ProtoMessage() {}

func (x *AuthorizeSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_eventsauth_v1_eventsauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeSignRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeSignRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeSignRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AuthorizeSignRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *AuthorizeSignRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type AuthorizeSignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mirror values of gateway.controlplane.v1.SubscribeAuthCode.
	// Encoded as int32 here to avoid a cross-package proto import.
	// 1 = OK, 7 = DENIED, etc. See SubscribeAuthCode in control.proto.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Optional, surfaced to operators in logs. Never leaked to clients.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeSignResponse) Reset() {
	*x = AuthorizeSignResponse{}
	mi := &file_gw_proto_eventsauth_v1_eventsauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeSignResponse) ProtoMessage() {}

func (x *AuthorizeSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_eventsauth_v1_eventsauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeSignResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeSignResponse) Descriptor() ([]byte, []int) {
	return file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeSignResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthorizeSignResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gw_proto_eventsauth_v1_eventsauth_proto protoreflect.FileDescriptor

const file_gw_proto_eventsauth_v1_eventsauth_proto_rawDesc = "" +
	"\n" +
	"'gw/proto/eventsauth/v1/eventsauth.proto\x12\x15gateway.eventsauth.v1\"x\n" +
	"\x14AuthorizeSignRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"C\n" +
	"\x15AuthorizeSignResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x84\x01\n" +
	"\x16SubscriptionAuthorizer\x12j\n" +
	"\rAuthorizeSign\x12+.gateway.eventsauth.v1.AuthorizeSignRequest\x1a,.gateway.eventsauth.v1.AuthorizeSignResponseBAZ?github.com/iodesystems/gwag/gw/proto/eventsauth/v1;eventsauthv1b\x06proto3"

var (
	file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescOnce sync.Once
	file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescData []byte
)

func file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescGZIP() []byte {
	file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescOnce.Do(func() {
		file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_eventsauth_v1_eventsauth_proto_rawDesc), len(file_gw_proto_eventsauth_v1_eventsauth_proto_rawDesc)))
	})
	return file_gw_proto_eventsauth_v1_eventsauth_proto_rawDescData
}

var file_gw_proto_eventsauth_v1_eventsauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gw_proto_eventsauth_v1_eventsauth_proto_goTypes = []any{
	(*AuthorizeSignRequest)(nil),  // 0: gateway.eventsauth.v1.AuthorizeSignRequest
	(*AuthorizeSignResponse)(nil), // 1: gateway.eventsauth.v1.AuthorizeSignResponse
}
var file_gw_proto_eventsauth_v1_eventsauth_proto_depIdxs = []int32{
	0, // 0: gateway.eventsauth.v1.SubscriptionAuthorizer.AuthorizeSign:input_type -> gateway.eventsauth.v1.AuthorizeSignRequest
	1, // 1: gateway.eventsauth.v1.SubscriptionAuthorizer.AuthorizeSign:output_type -> gateway.eventsauth.v1.AuthorizeSignResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gw_proto_eventsauth_v1_eventsauth_proto_init() }
func file_gw_proto_eventsauth_v1_eventsauth_proto_init() {
	if File_gw_proto_eventsauth_v1_eventsauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_eventsauth_v1_eventsauth_proto_rawDesc), len(file_gw_proto_eventsauth_v1_eventsauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_eventsauth_v1_eventsauth_proto_goTypes,
		DependencyIndexes: file_gw_proto_eventsauth_v1_eventsauth_proto_depIdxs,
		MessageInfos:      file_gw_proto_eventsauth_v1_eventsauth_proto_msgTypes,
	}.Build()
	File_gw_proto_eventsauth_v1_eventsauth_proto = out.File
	file_gw_proto_eventsauth_v1_eventsauth_proto_goTypes = nil
	file_gw_proto_eventsauth_v1_eventsauth_proto_depIdxs = nil
}
