// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gw/proto/eventsauth/v1/eventsauth.proto

package eventsauthv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionAuthorizer_AuthorizeSign_FullMethodName = "/gateway.eventsauth.v1.SubscriptionAuthorizer/AuthorizeSign"
)

// SubscriptionAuthorizerClient is the client API for SubscriptionAuthorizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubscriptionAuthorizer is the optional delegate the gateway calls
// when SignSubscriptionToken is invoked. Implement it in your authz
// service and register it with namespace "_events_auth" / version v1.
//
// The gateway looks up the registered pool, picks a replica via the
// usual least-in-flight path, and sends AuthorizeSign before HMAC-
// signing the token. If the response code is not OK, the gateway
// returns that code to the caller without minting a token.
type SubscriptionAuthorizerClient interface {
	AuthorizeSign(ctx context.Context, in *AuthorizeSignRequest, opts ...grpc.CallOption) (*AuthorizeSignResponse, error)
}

type subscriptionAuthorizerClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionAuthorizerClient(cc grpc.ClientConnInterface) SubscriptionAuthorizerClient {
	return &subscriptionAuthorizerClient{cc}
}

func (c *subscriptionAuthorizerClient) AuthorizeSign(ctx context.Context, in *AuthorizeSignRequest, opts ...grpc.CallOption) (*AuthorizeSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeSignResponse)
	err := c.cc.Invoke(ctx, SubscriptionAuthorizer_AuthorizeSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionAuthorizerServer is the server API for SubscriptionAuthorizer service.
// All implementations must embed UnimplementedSubscriptionAuthorizerServer
// for forward compatibility.
//
// SubscriptionAuthorizer is the optional delegate the gateway calls
// when SignSubscriptionToken is invoked. Implement it in your authz
// service and register it with namespace "_events_auth" / version v1.
//
// The gateway looks up the registered pool, picks a replica via the
// usual least-in-flight path, and sends AuthorizeSign before HMAC-
// signing the token. If the response code is not OK, the gateway
// returns that code to the caller without minting a token.
type SubscriptionAuthorizerServer interface {
	AuthorizeSign(context.Context, *AuthorizeSignRequest) (*AuthorizeSignResponse, error)
	mustEmbedUnimplementedSubscriptionAuthorizerServer()
}

// UnimplementedSubscriptionAuthorizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionAuthorizerServer struct{}

func (UnimplementedSubscriptionAuthorizerServer) AuthorizeSign(context.Context, *AuthorizeSignRequest) (*AuthorizeSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeSign not implemented")
}
func (UnimplementedSubscriptionAuthorizerServer) mustEmbedUnimplementedSubscriptionAuthorizerServer() {
}
func (UnimplementedSubscriptionAuthorizerServer) testEmbeddedByValue() {}

// UnsafeSubscriptionAuthorizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionAuthorizerServer will
// result in compilation errors.
type UnsafeSubscriptionAuthorizerServer interface {
	mustEmbedUnimplementedSubscriptionAuthorizerServer()
}

func RegisterSubscriptionAuthorizerServer(s grpc.ServiceRegistrar, srv SubscriptionAuthorizerServer) {
	// If the following call panics, it indicates UnimplementedSubscriptionAuthorizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionAuthorizer_ServiceDesc, srv)
}

func _SubscriptionAuthorizer_AuthorizeSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionAuthorizerServer).AuthorizeSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionAuthorizer_AuthorizeSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionAuthorizerServer).AuthorizeSign(ctx, req.(*AuthorizeSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionAuthorizer_ServiceDesc is the grpc.ServiceDesc for SubscriptionAuthorizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionAuthorizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.eventsauth.v1.SubscriptionAuthorizer",
	HandlerType: (*SubscriptionAuthorizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeSign",
			Handler:    _SubscriptionAuthorizer_AuthorizeSign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gw/proto/eventsauth/v1/eventsauth.proto",
}
