// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/ps/v1/options.proto

package psv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChannelBinding is the proto-declarative payload-type binding the
// gateway extracts at slot bake. A message whose options carry
// `(gwag.ps.binding) = { pattern: "events.orders.*.update" }` declares
// that any event delivered on a channel matching `pattern` is wire-
// compatible with that message. The pattern grammar is NATS-style
// (segments split on `.`, `*` matches one segment, `>` matches the
// rest), identical to the grammar `WithChannelAuth` uses.
//
// The binding rides in the proto's source bytes — both the boot-time
// `AddProto` path and the control-plane `proto_source` path carry the
// extension end-to-end without a side channel. The gateway aggregates
// across all registered slots into a pattern→message-FQN lookup;
// matched events get their `Event.payload_type` stamped at delivery
// so subscribers can cross-reference the descriptor in
// `/schema/proto?service=...` for decoding.
type ChannelBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NATS-style channel subject pattern this message binds to. Required.
	Pattern       string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelBinding) Reset() {
	*x = ChannelBinding{}
	mi := &file_gw_proto_ps_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelBinding) ProtoMessage() {}

func (x *ChannelBinding) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_ps_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelBinding.ProtoReflect.Descriptor instead.
func (*ChannelBinding) Descriptor() ([]byte, []int) {
	return file_gw_proto_ps_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelBinding) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

var file_gw_proto_ps_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ChannelBinding)(nil),
		Field:         51234,
		Name:          "gwag.ps.v1.binding",
		Tag:           "bytes,51234,opt,name=binding",
		Filename:      "gw/proto/ps/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Custom option in the 50000–99999 range reserved for internal use
	// (per protobuf descriptor.proto guidance — production options would
	// request a globally-unique number from the protobuf registry; this
	// one is gateway-internal so the in-house range is correct).
	//
	// optional gwag.ps.v1.ChannelBinding binding = 51234;
	E_Binding = &file_gw_proto_ps_v1_options_proto_extTypes[0]
)

var File_gw_proto_ps_v1_options_proto protoreflect.FileDescriptor

const file_gw_proto_ps_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x1cgw/proto/ps/v1/options.proto\x12\n" +
	"gwag.ps.v1\x1a google/protobuf/descriptor.proto\"*\n" +
	"\x0eChannelBinding\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern:Z\n" +
	"\abinding\x12\x1f.google.protobuf.MessageOptions\x18\xa2\x90\x03 \x01(\v2\x1a.gwag.ps.v1.ChannelBindingR\abinding\x88\x01\x01B1Z/github.com/iodesystems/gwag/gw/proto/ps/v1;psv1b\x06proto3"

var (
	file_gw_proto_ps_v1_options_proto_rawDescOnce sync.Once
	file_gw_proto_ps_v1_options_proto_rawDescData []byte
)

func file_gw_proto_ps_v1_options_proto_rawDescGZIP() []byte {
	file_gw_proto_ps_v1_options_proto_rawDescOnce.Do(func() {
		file_gw_proto_ps_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_ps_v1_options_proto_rawDesc), len(file_gw_proto_ps_v1_options_proto_rawDesc)))
	})
	return file_gw_proto_ps_v1_options_proto_rawDescData
}

var file_gw_proto_ps_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gw_proto_ps_v1_options_proto_goTypes = []any{
	(*ChannelBinding)(nil),              // 0: gwag.ps.v1.ChannelBinding
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_gw_proto_ps_v1_options_proto_depIdxs = []int32{
	1, // 0: gwag.ps.v1.binding:extendee -> google.protobuf.MessageOptions
	0, // 1: gwag.ps.v1.binding:type_name -> gwag.ps.v1.ChannelBinding
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gw_proto_ps_v1_options_proto_init() }
func file_gw_proto_ps_v1_options_proto_init() {
	if File_gw_proto_ps_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_ps_v1_options_proto_rawDesc), len(file_gw_proto_ps_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_gw_proto_ps_v1_options_proto_goTypes,
		DependencyIndexes: file_gw_proto_ps_v1_options_proto_depIdxs,
		MessageInfos:      file_gw_proto_ps_v1_options_proto_msgTypes,
		ExtensionInfos:    file_gw_proto_ps_v1_options_proto_extTypes,
	}.Build()
	File_gw_proto_ps_v1_options_proto = out.File
	file_gw_proto_ps_v1_options_proto_goTypes = nil
	file_gw_proto_ps_v1_options_proto_depIdxs = nil
}
