// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/ps/v1/ps.proto

package psv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target channel subject (e.g. `events.orders.42.update`). Wildcards
	// are not valid on publish.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Opaque payload bytes encoded as a string — JSON, base64, or any
	// agreed encoding-of-the-day. Channel->message-type bindings give
	// subscribers the descriptor to deserialize against; the broker
	// itself does not parse.
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// HMAC token over (channel, ts), signed by a key the operator
	// controls. Ignored when the channel pattern's auth tier is `open`.
	Hmac string `protobuf:"bytes,3,opt,name=hmac,proto3" json:"hmac,omitempty"`
	// Wall-clock unix timestamp the client used when signing. Bounded by
	// the operator's skew window to prevent replay.
	Ts            int64 `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubRequest) Reset() {
	*x = PubRequest{}
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubRequest) ProtoMessage() {}

func (x *PubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubRequest.ProtoReflect.Descriptor instead.
func (*PubRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_ps_v1_ps_proto_rawDescGZIP(), []int{0}
}

func (x *PubRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PubRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PubRequest) GetHmac() string {
	if x != nil {
		return x.Hmac
	}
	return ""
}

func (x *PubRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type PubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubResponse) Reset() {
	*x = PubResponse{}
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubResponse) ProtoMessage() {}

func (x *PubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubResponse.ProtoReflect.Descriptor instead.
func (*PubResponse) Descriptor() ([]byte, []int) {
	return file_gw_proto_ps_v1_ps_proto_rawDescGZIP(), []int{1}
}

type SubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel subject or NATS-wildcard pattern (`events.orders.*.update`,
	// `events.orders.>`). HMAC, when required, binds to this literal
	// string.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// HMAC token over (channel, ts). Ignored when the matched auth tier
	// is `open`.
	Hmac string `protobuf:"bytes,2,opt,name=hmac,proto3" json:"hmac,omitempty"`
	// Wall-clock unix timestamp the client used when signing. Bounded by
	// the operator's skew window.
	Ts            int64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_ps_v1_ps_proto_rawDescGZIP(), []int{2}
}

func (x *SubRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SubRequest) GetHmac() string {
	if x != nil {
		return x.Hmac
	}
	return ""
}

func (x *SubRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved channel subject the event was published on (always
	// concrete, even when the subscriber asked for a wildcard).
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Payload bytes as published. Encoding is whatever the publisher
	// wrote; the broker is opaque to it.
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Fully-qualified proto message name the payload conforms to, when a
	// WithChannelBinding pattern matched the channel; empty otherwise.
	// Subscribers cross-reference via `/schema/proto?service=...` to get
	// the descriptor for decoding.
	PayloadType string `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	// Wall-clock unix timestamp the event was accepted at Pub entry.
	Ts            int64 `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_ps_v1_ps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_gw_proto_ps_v1_ps_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

var File_gw_proto_ps_v1_ps_proto protoreflect.FileDescriptor

const file_gw_proto_ps_v1_ps_proto_rawDesc = "" +
	"\n" +
	"\x17gw/proto/ps/v1/ps.proto\x12\n" +
	"gwag.ps.v1\"d\n" +
	"\n" +
	"PubRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x12\n" +
	"\x04hmac\x18\x03 \x01(\tR\x04hmac\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\"\r\n" +
	"\vPubResponse\"J\n" +
	"\n" +
	"SubRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x12\n" +
	"\x04hmac\x18\x02 \x01(\tR\x04hmac\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\"n\n" +
	"\x05Event\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12!\n" +
	"\fpayload_type\x18\x03 \x01(\tR\vpayloadType\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts2t\n" +
	"\x06PubSub\x126\n" +
	"\x03Pub\x12\x16.gwag.ps.v1.PubRequest\x1a\x17.gwag.ps.v1.PubResponse\x122\n" +
	"\x03Sub\x12\x16.gwag.ps.v1.SubRequest\x1a\x11.gwag.ps.v1.Event0\x01B1Z/github.com/iodesystems/gwag/gw/proto/ps/v1;psv1b\x06proto3"

var (
	file_gw_proto_ps_v1_ps_proto_rawDescOnce sync.Once
	file_gw_proto_ps_v1_ps_proto_rawDescData []byte
)

func file_gw_proto_ps_v1_ps_proto_rawDescGZIP() []byte {
	file_gw_proto_ps_v1_ps_proto_rawDescOnce.Do(func() {
		file_gw_proto_ps_v1_ps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_ps_v1_ps_proto_rawDesc), len(file_gw_proto_ps_v1_ps_proto_rawDesc)))
	})
	return file_gw_proto_ps_v1_ps_proto_rawDescData
}

var file_gw_proto_ps_v1_ps_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gw_proto_ps_v1_ps_proto_goTypes = []any{
	(*PubRequest)(nil),  // 0: gwag.ps.v1.PubRequest
	(*PubResponse)(nil), // 1: gwag.ps.v1.PubResponse
	(*SubRequest)(nil),  // 2: gwag.ps.v1.SubRequest
	(*Event)(nil),       // 3: gwag.ps.v1.Event
}
var file_gw_proto_ps_v1_ps_proto_depIdxs = []int32{
	0, // 0: gwag.ps.v1.PubSub.Pub:input_type -> gwag.ps.v1.PubRequest
	2, // 1: gwag.ps.v1.PubSub.Sub:input_type -> gwag.ps.v1.SubRequest
	1, // 2: gwag.ps.v1.PubSub.Pub:output_type -> gwag.ps.v1.PubResponse
	3, // 3: gwag.ps.v1.PubSub.Sub:output_type -> gwag.ps.v1.Event
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gw_proto_ps_v1_ps_proto_init() }
func file_gw_proto_ps_v1_ps_proto_init() {
	if File_gw_proto_ps_v1_ps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_ps_v1_ps_proto_rawDesc), len(file_gw_proto_ps_v1_ps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_ps_v1_ps_proto_goTypes,
		DependencyIndexes: file_gw_proto_ps_v1_ps_proto_depIdxs,
		MessageInfos:      file_gw_proto_ps_v1_ps_proto_msgTypes,
	}.Build()
	File_gw_proto_ps_v1_ps_proto = out.File
	file_gw_proto_ps_v1_ps_proto_goTypes = nil
	file_gw_proto_ps_v1_ps_proto_depIdxs = nil
}
