// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gw/proto/ps/v1/ps.proto

package psv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PubSub_Pub_FullMethodName = "/gwag.ps.v1.PubSub/Pub"
	PubSub_Sub_FullMethodName = "/gwag.ps.v1.PubSub/Sub"
)

// PubSubClient is the client API for PubSub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PubSub is the gateway-internal pub/sub primitive. It renders as
// `Mutation.ps.pub(channel, payload, hmac, ts)` and
// `Subscription.ps.sub(channel, hmac, ts) -> ps.Event` via the same
// nested-namespace convention `admin.listPeers` already uses.
//
// The proto exists for IR / SDL / MCP / admin-listing parity with every
// other ingest path. Runtime is in-process: there is no proxy service
// behind these RPCs; dispatch resolves to a Go handler registered with
// the gateway.
type PubSubClient interface {
	// Pub publishes a single payload onto a channel. Auth is governed by
	// the operator's WithChannelAuth(pattern, tier) registrations; default
	// tier when no pattern matches is hmac.
	Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error)
	// Sub opens a subscriber stream for a channel (NATS-style wildcards
	// supported: `events.orders.>`). HMAC binds to the literal pattern
	// string the client requests, not a concrete channel.
	Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type pubSubClient struct {
	cc grpc.ClientConnInterface
}

func NewPubSubClient(cc grpc.ClientConnInterface) PubSubClient {
	return &pubSubClient{cc}
}

func (c *pubSubClient) Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PubResponse)
	err := c.cc.Invoke(ctx, PubSub_Pub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) Sub(ctx context.Context, in *SubRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubSub_ServiceDesc.Streams[0], PubSub_Sub_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_SubClient = grpc.ServerStreamingClient[Event]

// PubSubServer is the server API for PubSub service.
// All implementations must embed UnimplementedPubSubServer
// for forward compatibility.
//
// PubSub is the gateway-internal pub/sub primitive. It renders as
// `Mutation.ps.pub(channel, payload, hmac, ts)` and
// `Subscription.ps.sub(channel, hmac, ts) -> ps.Event` via the same
// nested-namespace convention `admin.listPeers` already uses.
//
// The proto exists for IR / SDL / MCP / admin-listing parity with every
// other ingest path. Runtime is in-process: there is no proxy service
// behind these RPCs; dispatch resolves to a Go handler registered with
// the gateway.
type PubSubServer interface {
	// Pub publishes a single payload onto a channel. Auth is governed by
	// the operator's WithChannelAuth(pattern, tier) registrations; default
	// tier when no pattern matches is hmac.
	Pub(context.Context, *PubRequest) (*PubResponse, error)
	// Sub opens a subscriber stream for a channel (NATS-style wildcards
	// supported: `events.orders.>`). HMAC binds to the literal pattern
	// string the client requests, not a concrete channel.
	Sub(*SubRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedPubSubServer()
}

// UnimplementedPubSubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPubSubServer struct{}

func (UnimplementedPubSubServer) Pub(context.Context, *PubRequest) (*PubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pub not implemented")
}
func (UnimplementedPubSubServer) Sub(*SubRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedPubSubServer) mustEmbedUnimplementedPubSubServer() {}
func (UnimplementedPubSubServer) testEmbeddedByValue()                {}

// UnsafePubSubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubSubServer will
// result in compilation errors.
type UnsafePubSubServer interface {
	mustEmbedUnimplementedPubSubServer()
}

func RegisterPubSubServer(s grpc.ServiceRegistrar, srv PubSubServer) {
	// If the following call panics, it indicates UnimplementedPubSubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PubSub_ServiceDesc, srv)
}

func _PubSub_Pub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).Pub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSub_Pub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).Pub(ctx, req.(*PubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_Sub_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubSubServer).Sub(m, &grpc.GenericServerStream[SubRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_SubServer = grpc.ServerStreamingServer[Event]

// PubSub_ServiceDesc is the grpc.ServiceDesc for PubSub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubSub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gwag.ps.v1.PubSub",
	HandlerType: (*PubSubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pub",
			Handler:    _PubSub_Pub_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sub",
			Handler:       _PubSub_Sub_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gw/proto/ps/v1/ps.proto",
}
