// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gw/proto/controlplane/v1/control.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Register_FullMethodName              = "/gateway.controlplane.v1.ControlPlane/Register"
	ControlPlane_Heartbeat_FullMethodName             = "/gateway.controlplane.v1.ControlPlane/Heartbeat"
	ControlPlane_Deregister_FullMethodName            = "/gateway.controlplane.v1.ControlPlane/Deregister"
	ControlPlane_ListRegistrations_FullMethodName     = "/gateway.controlplane.v1.ControlPlane/ListRegistrations"
	ControlPlane_ListPeers_FullMethodName             = "/gateway.controlplane.v1.ControlPlane/ListPeers"
	ControlPlane_ForgetPeer_FullMethodName            = "/gateway.controlplane.v1.ControlPlane/ForgetPeer"
	ControlPlane_ListServices_FullMethodName          = "/gateway.controlplane.v1.ControlPlane/ListServices"
	ControlPlane_SignSubscriptionToken_FullMethodName = "/gateway.controlplane.v1.ControlPlane/SignSubscriptionToken"
	ControlPlane_RetractStable_FullMethodName         = "/gateway.controlplane.v1.ControlPlane/RetractStable"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane is the API services use to register themselves with a
// running gateway. The flow:
//
//  1. Service starts its gRPC server on some addr.
//  2. Service calls Register with that addr and the list of services
//     it hosts (one address can host multiple services).
//  3. Service holds a heartbeat loop that calls Heartbeat at TtlSeconds/3.
//  4. On graceful shutdown, service calls Deregister.
//  5. If heartbeats stop coming for >TtlSeconds, the gateway evicts
//     the registration on its own.
type ControlPlaneClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	ListRegistrations(ctx context.Context, in *ListRegistrationsRequest, opts ...grpc.CallOption) (*ListRegistrationsResponse, error)
	// ListPeers returns all gateway peers known to the cluster (alive
	// entries in the peers KV bucket). Useful for operators picking
	// which peer to forget.
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	// ForgetPeer removes a disconnected peer from the cluster's peer
	// bucket and shrinks the registry stream's replica count if the
	// remaining peer count is now lower. Refuses if the peer is still
	// alive (its KV entry hasn't expired) — operators must wait for
	// the heartbeat-miss window before forgetting.
	ForgetPeer(ctx context.Context, in *ForgetPeerRequest, opts ...grpc.CallOption) (*ForgetPeerResponse, error)
	// ListServices returns the (namespace, version, hash, replica_count)
	// tuples currently live in the cluster. The hash is the canonical
	// FileDescriptorSet SHA256, suitable for cross-cluster parity
	// checks (dev/prod promotion gating).
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// SignSubscriptionToken mints an HMAC token for a subscription
	// channel. Callers are typically privileged services that have
	// already authenticated the end user; the gateway optionally
	// consults a registered SubscriptionAuthorizer delegate before
	// signing.
	SignSubscriptionToken(ctx context.Context, in *SignSubscriptionTokenRequest, opts ...grpc.CallOption) (*SignSubscriptionTokenResponse, error)
	// RetractStable moves a namespace's `stable` alias backward to
	// `target_vN`. Operator-driven; never automatic. Plan §4: stable
	// is monotonic across registration, so the only way it decreases
	// is this RPC (and the corresponding admin/retractStable huma
	// route). Refuses to skip past a vN that isn't currently in the
	// build — `target_vN` must have a live registration so `stable`
	// continues to surface a real schema. Persists in the cluster
	// stable KV bucket so the retract survives restarts and reaches
	// every peer; emits a service-change event so peers re-render
	// immediately.
	RetractStable(ctx context.Context, in *RetractStableRequest, opts ...grpc.CallOption) (*RetractStableResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListRegistrations(ctx context.Context, in *ListRegistrationsRequest, opts ...grpc.CallOption) (*ListRegistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegistrationsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ForgetPeer(ctx context.Context, in *ForgetPeerRequest, opts ...grpc.CallOption) (*ForgetPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetPeerResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ForgetPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) SignSubscriptionToken(ctx context.Context, in *SignSubscriptionTokenRequest, opts ...grpc.CallOption) (*SignSubscriptionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignSubscriptionTokenResponse)
	err := c.cc.Invoke(ctx, ControlPlane_SignSubscriptionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RetractStable(ctx context.Context, in *RetractStableRequest, opts ...grpc.CallOption) (*RetractStableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractStableResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RetractStable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane is the API services use to register themselves with a
// running gateway. The flow:
//
//  1. Service starts its gRPC server on some addr.
//  2. Service calls Register with that addr and the list of services
//     it hosts (one address can host multiple services).
//  3. Service holds a heartbeat loop that calls Heartbeat at TtlSeconds/3.
//  4. On graceful shutdown, service calls Deregister.
//  5. If heartbeats stop coming for >TtlSeconds, the gateway evicts
//     the registration on its own.
type ControlPlaneServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	ListRegistrations(context.Context, *ListRegistrationsRequest) (*ListRegistrationsResponse, error)
	// ListPeers returns all gateway peers known to the cluster (alive
	// entries in the peers KV bucket). Useful for operators picking
	// which peer to forget.
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	// ForgetPeer removes a disconnected peer from the cluster's peer
	// bucket and shrinks the registry stream's replica count if the
	// remaining peer count is now lower. Refuses if the peer is still
	// alive (its KV entry hasn't expired) — operators must wait for
	// the heartbeat-miss window before forgetting.
	ForgetPeer(context.Context, *ForgetPeerRequest) (*ForgetPeerResponse, error)
	// ListServices returns the (namespace, version, hash, replica_count)
	// tuples currently live in the cluster. The hash is the canonical
	// FileDescriptorSet SHA256, suitable for cross-cluster parity
	// checks (dev/prod promotion gating).
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// SignSubscriptionToken mints an HMAC token for a subscription
	// channel. Callers are typically privileged services that have
	// already authenticated the end user; the gateway optionally
	// consults a registered SubscriptionAuthorizer delegate before
	// signing.
	SignSubscriptionToken(context.Context, *SignSubscriptionTokenRequest) (*SignSubscriptionTokenResponse, error)
	// RetractStable moves a namespace's `stable` alias backward to
	// `target_vN`. Operator-driven; never automatic. Plan §4: stable
	// is monotonic across registration, so the only way it decreases
	// is this RPC (and the corresponding admin/retractStable huma
	// route). Refuses to skip past a vN that isn't currently in the
	// build — `target_vN` must have a live registration so `stable`
	// continues to surface a real schema. Persists in the cluster
	// stable KV bucket so the retract survives restarts and reaches
	// every peer; emits a service-change event so peers re-render
	// immediately.
	RetractStable(context.Context, *RetractStableRequest) (*RetractStableResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedControlPlaneServer) ListRegistrations(context.Context, *ListRegistrationsRequest) (*ListRegistrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRegistrations not implemented")
}
func (UnimplementedControlPlaneServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedControlPlaneServer) ForgetPeer(context.Context, *ForgetPeerRequest) (*ForgetPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetPeer not implemented")
}
func (UnimplementedControlPlaneServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedControlPlaneServer) SignSubscriptionToken(context.Context, *SignSubscriptionTokenRequest) (*SignSubscriptionTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignSubscriptionToken not implemented")
}
func (UnimplementedControlPlaneServer) RetractStable(context.Context, *RetractStableRequest) (*RetractStableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetractStable not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListRegistrations(ctx, req.(*ListRegistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ForgetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ForgetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ForgetPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ForgetPeer(ctx, req.(*ForgetPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_SignSubscriptionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignSubscriptionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SignSubscriptionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_SignSubscriptionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SignSubscriptionToken(ctx, req.(*SignSubscriptionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RetractStable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetractStableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RetractStable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RetractStable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RetractStable(ctx, req.(*RetractStableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.controlplane.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ControlPlane_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _ControlPlane_Deregister_Handler,
		},
		{
			MethodName: "ListRegistrations",
			Handler:    _ControlPlane_ListRegistrations_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _ControlPlane_ListPeers_Handler,
		},
		{
			MethodName: "ForgetPeer",
			Handler:    _ControlPlane_ForgetPeer_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ControlPlane_ListServices_Handler,
		},
		{
			MethodName: "SignSubscriptionToken",
			Handler:    _ControlPlane_SignSubscriptionToken_Handler,
		},
		{
			MethodName: "RetractStable",
			Handler:    _ControlPlane_RetractStable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gw/proto/controlplane/v1/control.proto",
}
