// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeAuthCode is the result of an attempted subscribe. Both the
// gateway-side HMAC verification and the SubscriptionAuthorizer
// delegate emit codes from this enum, so operators get consistent
// error semantics across both paths.
type SubscribeAuthCode int32

const (
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_UNSPECIFIED SubscribeAuthCode = 0
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_OK          SubscribeAuthCode = 1
	// HMAC verification failures (gateway-side):
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_TOO_OLD            SubscribeAuthCode = 2 // timestamp older than skew window
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_TOO_NEW            SubscribeAuthCode = 3 // timestamp from the future
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_SIGNATURE_MISMATCH SubscribeAuthCode = 4
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_MALFORMED          SubscribeAuthCode = 5 // missing/garbled hmac or timestamp args
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_UNKNOWN_KID        SubscribeAuthCode = 6 // key id not in active set (rotation)
	// Delegate-side outcomes:
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_DENIED         SubscribeAuthCode = 7 // delegate said no
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_UNAVAILABLE    SubscribeAuthCode = 8 // delegate didn't respond / errored
	SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_NOT_CONFIGURED SubscribeAuthCode = 9 // mode requires config that isn't set
)

// Enum value maps for SubscribeAuthCode.
var (
	SubscribeAuthCode_name = map[int32]string{
		0: "SUBSCRIBE_AUTH_CODE_UNSPECIFIED",
		1: "SUBSCRIBE_AUTH_CODE_OK",
		2: "SUBSCRIBE_AUTH_CODE_TOO_OLD",
		3: "SUBSCRIBE_AUTH_CODE_TOO_NEW",
		4: "SUBSCRIBE_AUTH_CODE_SIGNATURE_MISMATCH",
		5: "SUBSCRIBE_AUTH_CODE_MALFORMED",
		6: "SUBSCRIBE_AUTH_CODE_UNKNOWN_KID",
		7: "SUBSCRIBE_AUTH_CODE_DENIED",
		8: "SUBSCRIBE_AUTH_CODE_UNAVAILABLE",
		9: "SUBSCRIBE_AUTH_CODE_NOT_CONFIGURED",
	}
	SubscribeAuthCode_value = map[string]int32{
		"SUBSCRIBE_AUTH_CODE_UNSPECIFIED":        0,
		"SUBSCRIBE_AUTH_CODE_OK":                 1,
		"SUBSCRIBE_AUTH_CODE_TOO_OLD":            2,
		"SUBSCRIBE_AUTH_CODE_TOO_NEW":            3,
		"SUBSCRIBE_AUTH_CODE_SIGNATURE_MISMATCH": 4,
		"SUBSCRIBE_AUTH_CODE_MALFORMED":          5,
		"SUBSCRIBE_AUTH_CODE_UNKNOWN_KID":        6,
		"SUBSCRIBE_AUTH_CODE_DENIED":             7,
		"SUBSCRIBE_AUTH_CODE_UNAVAILABLE":        8,
		"SUBSCRIBE_AUTH_CODE_NOT_CONFIGURED":     9,
	}
)

func (x SubscribeAuthCode) Enum() *SubscribeAuthCode {
	p := new(SubscribeAuthCode)
	*p = x
	return p
}

func (x SubscribeAuthCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeAuthCode) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (SubscribeAuthCode) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x SubscribeAuthCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeAuthCode.Descriptor instead.
func (SubscribeAuthCode) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC destination where the registered services live; passed
	// verbatim to grpc.NewClient on the gateway side.
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// One or more services to mount at `addr`. The gateway exposes each
	// under its requested namespace. Collisions across registrations are
	// an error and reject the entire Register call.
	Services []*ServiceBinding `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	// How long the gateway should retain the registration without seeing
	// a Heartbeat. 0 means "use server default" (currently 30s).
	TtlSeconds uint32 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Free-form. Echoed in ListRegistrations for operator debugging
	// (e.g. "greeter@gke-cluster-1@pod-abc"). Not used for routing.
	InstanceId    string `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterRequest) GetServices() []*ServiceBinding {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *RegisterRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ServiceBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GraphQL namespace under which this service's RPCs appear. Defaults
	// to the proto file's stem if empty.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Standard FileDescriptorSet bytes (what `protoc -o` emits, or what
	// protodesc.ToFileDescriptorProto + Marshal produces). Must include
	// every transitive import the proto needs to type-check.
	//
	// Mutually exclusive with `openapi_spec`: a binding registers either
	// a proto-described gRPC service or an OpenAPI-described HTTP
	// service. Both unset / both set is an error.
	FileDescriptorSet []byte `protobuf:"bytes,2,opt,name=file_descriptor_set,json=fileDescriptorSet,proto3" json:"file_descriptor_set,omitempty"`
	// Optional: the specific file within file_descriptor_set whose
	// services should be mounted. Defaults to the LAST file in the set,
	// which is conventionally the dependent file rather than its imports.
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Service version. Accepted values: "unstable" (the mutable
	// single-overwrite slot — each register replaces the prior one for
	// this namespace) or "vN" for integer N ≥ 1 (locked once
	// registered; differing schema-hash for an existing vN is rejected
	// as AlreadyExists, "cut v(N+1)"). "stable" is a computed alias to
	// the highest-ever-seen vN and is NOT directly registerable —
	// requests with version="stable" are rejected with a clear error.
	// Bare digits ("3"), uppercase ("V3"), zero-prefixed ("v0", "v01")
	// and other strings are rejected. Empty defaults to "v1" for
	// back-compat with services that don't set the field.
	//
	// Multiple vN versions of the same namespace coexist; the highest
	// live vN is "latest" and surfaces flat under the namespace. Older
	// versions are addressable via name-disambiguated fields
	// ("<ns>_<vN>_<op>" / "<ns>_<vN>_<TypeName>") carrying GraphQL
	// @deprecated. Honored for all three binding forms (proto / openapi
	// / graphql).
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Raw OpenAPI 3.x spec bytes (JSON or YAML; kin-openapi parses
	// either). Mutually exclusive with `file_descriptor_set`. When set,
	// RegisterRequest.addr is the HTTP base URL the gateway dispatches
	// to (e.g. "https://billing.internal" or "http://localhost:8080").
	OpenapiSpec []byte `protobuf:"bytes,5,opt,name=openapi_spec,json=openapiSpec,proto3" json:"openapi_spec,omitempty"`
	// Endpoint URL of an upstream GraphQL service to ingest under this
	// namespace. Mutually exclusive with `file_descriptor_set` and
	// `openapi_spec`. The receiving gateway runs the canonical
	// introspection query against this endpoint at Register time,
	// mirrors every type with a `<namespace>_` prefix, and forwards
	// dispatches back to the same endpoint. RegisterRequest.addr is
	// ignored for GraphQL bindings — the endpoint URL carries the
	// dispatch destination too.
	GraphqlEndpoint string `protobuf:"bytes,6,opt,name=graphql_endpoint,json=graphqlEndpoint,proto3" json:"graphql_endpoint,omitempty"`
	// Caps simultaneous unary dispatches against this (namespace,
	// version) on the receiving gateway. Overrides the gateway-wide
	// BackpressureOptions.MaxInflight default for this one binding.
	// 0 → fall back to the gateway default. Frozen at first
	// registration: later joins must agree (mismatched values reject).
	MaxConcurrency uint32 `protobuf:"varint,7,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	// Caps simultaneous unary dispatches against any single replica
	// behind this binding. Independent of max_concurrency — a 3-replica
	// service with max_concurrency_per_instance=50 holds at most 150
	// in-flight even if max_concurrency is higher. 0 → unbounded per
	// replica (only the service-level cap applies). Frozen at first
	// registration.
	MaxConcurrencyPerInstance uint32 `protobuf:"varint,8,opt,name=max_concurrency_per_instance,json=maxConcurrencyPerInstance,proto3" json:"max_concurrency_per_instance,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ServiceBinding) Reset() {
	*x = ServiceBinding{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceBinding) ProtoMessage() {}

func (x *ServiceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceBinding.ProtoReflect.Descriptor instead.
func (*ServiceBinding) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceBinding) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceBinding) GetFileDescriptorSet() []byte {
	if x != nil {
		return x.FileDescriptorSet
	}
	return nil
}

func (x *ServiceBinding) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ServiceBinding) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceBinding) GetOpenapiSpec() []byte {
	if x != nil {
		return x.OpenapiSpec
	}
	return nil
}

func (x *ServiceBinding) GetGraphqlEndpoint() string {
	if x != nil {
		return x.GraphqlEndpoint
	}
	return ""
}

func (x *ServiceBinding) GetMaxConcurrency() uint32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *ServiceBinding) GetMaxConcurrencyPerInstance() uint32 {
	if x != nil {
		return x.MaxConcurrencyPerInstance
	}
	return 0
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque token referenced by Heartbeat and Deregister. Treat as
	// unique per Register call.
	RegistrationId string `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	// The gateway's effective TTL, in case the request specified 0.
	TtlSeconds    uint32 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *RegisterResponse) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the registration is still live. False means the gateway
	// already evicted it (network partition, restart, etc.) and the
	// service should re-Register from scratch.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeregisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

type ListRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistrationsRequest) Reset() {
	*x = ListRegistrationsRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistrationsRequest) ProtoMessage() {}

func (x *ListRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*ListRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

type ListRegistrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*Registration        `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistrationsResponse) Reset() {
	*x = ListRegistrationsResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistrationsResponse) ProtoMessage() {}

func (x *ListRegistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistrationsResponse.ProtoReflect.Descriptor instead.
func (*ListRegistrationsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *ListRegistrationsResponse) GetRegistrations() []*Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

type Registration struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId      string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Addr                string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	InstanceId          string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	TtlSeconds          uint32                 `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	LastHeartbeatUnixMs uint64                 `protobuf:"varint,5,opt,name=last_heartbeat_unix_ms,json=lastHeartbeatUnixMs,proto3" json:"last_heartbeat_unix_ms,omitempty"`
	Namespaces          []string               `protobuf:"bytes,6,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *Registration) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *Registration) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Registration) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Registration) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Registration) GetLastHeartbeatUnixMs() uint64 {
	if x != nil {
		return x.LastHeartbeatUnixMs
	}
	return 0
}

func (x *Registration) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *ListPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable cluster identifier — what ForgetPeer takes.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Operator-friendly name (--node-name flag), if set.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Unix milliseconds when the peer first registered (this generation).
	// Used to detect re-joins after a forget.
	JoinedUnixMs  int64 `protobuf:"varint,3,opt,name=joined_unix_ms,json=joinedUnixMs,proto3" json:"joined_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *Peer) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetJoinedUnixMs() int64 {
	if x != nil {
		return x.JoinedUnixMs
	}
	return 0
}

type ForgetPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPeerRequest) Reset() {
	*x = ForgetPeerRequest{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPeerRequest) ProtoMessage() {}

func (x *ForgetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPeerRequest.ProtoReflect.Descriptor instead.
func (*ForgetPeerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *ForgetPeerRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ForgetPeerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if a peer entry was found and removed, false if the peer
	// was unknown (already forgotten or never seen).
	Removed bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	// Replica count after the forget. If unchanged, the cluster was
	// already at this size or below.
	NewReplicas   uint32 `protobuf:"varint,2,opt,name=new_replicas,json=newReplicas,proto3" json:"new_replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPeerResponse) Reset() {
	*x = ForgetPeerResponse{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPeerResponse) ProtoMessage() {}

func (x *ForgetPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPeerResponse.ProtoReflect.Descriptor instead.
func (*ForgetPeerResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *ForgetPeerResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *ForgetPeerResponse) GetNewReplicas() uint32 {
	if x != nil {
		return x.NewReplicas
	}
	return 0
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

type ListServicesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Services []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	// Per-namespace stable alias target. Keys are namespaces; values
	// are the integer N such that <ns>.stable currently aliases vN.
	// Plan §4: monotonic; advances at registration, decreases only via
	// RetractStable. Operators (and the UI) compute "this row is the
	// current stable target" by matching ServiceInfo.version == fmt
	// ("v%d", stable_vn[namespace]).
	StableVn      map[string]uint32 `protobuf:"bytes,3,rep,name=stable_vn,json=stableVn,proto3" json:"stable_vn,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetStableVn() map[string]uint32 {
	if x != nil {
		return x.StableVn
	}
	return nil
}

type ServiceInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version   string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// SHA256 of the canonicalised FileDescriptorSet, hex-encoded.
	// Identical bytes ⇒ identical hash across clusters/protoc versions.
	HashHex string `protobuf:"bytes,3,opt,name=hash_hex,json=hashHex,proto3" json:"hash_hex,omitempty"`
	// Number of live replicas backing this (namespace, version) pool.
	ReplicaCount  uint32 `protobuf:"varint,4,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfo) GetHashHex() string {
	if x != nil {
		return x.HashHex
	}
	return ""
}

func (x *ServiceInfo) GetReplicaCount() uint32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

type SignSubscriptionTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The exact NATS subject the token will sign — already-substituted,
	// e.g. "events.greeter.Greetings.alice". Wildcards ("*", ">") are
	// legal if the delegate authorizes them.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// How long the token should be considered valid (informational
	// for the verifier, which uses a wall-clock skew window).
	TtlSeconds int64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Optional key id selecting which entry of
	// SubscriptionAuthOptions.Secrets to sign with. Empty (default) uses
	// the legacy `Secret` field and the legacy single-key payload
	// "<channel>\n<timestamp>". Non-empty kid signs the rotated payload
	// "<kid>\n<channel>\n<timestamp>". UNKNOWN_KID is returned when the
	// gateway has no secret for the given kid.
	Kid           string `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignSubscriptionTokenRequest) Reset() {
	*x = SignSubscriptionTokenRequest{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignSubscriptionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignSubscriptionTokenRequest) ProtoMessage() {}

func (x *SignSubscriptionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignSubscriptionTokenRequest.ProtoReflect.Descriptor instead.
func (*SignSubscriptionTokenRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *SignSubscriptionTokenRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SignSubscriptionTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SignSubscriptionTokenRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

type RetractStableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GraphQL namespace whose `stable` alias should be retracted.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The vN to retract `stable` to. Must currently have a live
	// registration on the cluster — refusing the call when target_vN
	// isn't in the build prevents `stable` from pointing at a missing
	// schema. Must also be strictly less than the current stable
	// value; raising stable is the registration path, not this RPC.
	TargetVN      uint32 `protobuf:"varint,2,opt,name=target_v_n,json=targetVN,proto3" json:"target_v_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractStableRequest) Reset() {
	*x = RetractStableRequest{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractStableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractStableRequest) ProtoMessage() {}

func (x *RetractStableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractStableRequest.ProtoReflect.Descriptor instead.
func (*RetractStableRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *RetractStableRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RetractStableRequest) GetTargetVN() uint32 {
	if x != nil {
		return x.TargetVN
	}
	return 0
}

type RetractStableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable's vN before the retract. 0 when no stable was set.
	PriorVN uint32 `protobuf:"varint,1,opt,name=prior_v_n,json=priorVN,proto3" json:"prior_v_n,omitempty"`
	// Stable's vN after the retract. Equals the request's target_v_n
	// on success.
	NewVN         uint32 `protobuf:"varint,2,opt,name=new_v_n,json=newVN,proto3" json:"new_v_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractStableResponse) Reset() {
	*x = RetractStableResponse{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractStableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractStableResponse) ProtoMessage() {}

func (x *RetractStableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractStableResponse.ProtoReflect.Descriptor instead.
func (*RetractStableResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *RetractStableResponse) GetPriorVN() uint32 {
	if x != nil {
		return x.PriorVN
	}
	return 0
}

func (x *RetractStableResponse) GetNewVN() uint32 {
	if x != nil {
		return x.NewVN
	}
	return 0
}

type SignSubscriptionTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OK on success; otherwise the failure code (NOT_CONFIGURED if the
	// gateway has no secret, UNKNOWN_KID if the kid in the request has
	// no entry in Secrets, DENIED/UNAVAILABLE if the delegate refused).
	Code SubscribeAuthCode `protobuf:"varint,1,opt,name=code,proto3,enum=gateway.controlplane.v1.SubscribeAuthCode" json:"code,omitempty"`
	// Base64-encoded HMAC. Empty when code != OK.
	Hmac string `protobuf:"bytes,2,opt,name=hmac,proto3" json:"hmac,omitempty"`
	// Unix timestamp embedded in the token. 0 when code != OK.
	TimestampUnix int64 `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	// Operator-friendly explanation when code != OK.
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// The key id this token was signed with. Echoes the request's kid;
	// empty for legacy single-key signing. Subscribers must pass this
	// back as the `kid` arg on the subscribe field for the gateway to
	// resolve the matching secret.
	Kid           string `protobuf:"bytes,5,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignSubscriptionTokenResponse) Reset() {
	*x = SignSubscriptionTokenResponse{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignSubscriptionTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignSubscriptionTokenResponse) ProtoMessage() {}

func (x *SignSubscriptionTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignSubscriptionTokenResponse.ProtoReflect.Descriptor instead.
func (*SignSubscriptionTokenResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *SignSubscriptionTokenResponse) GetCode() SubscribeAuthCode {
	if x != nil {
		return x.Code
	}
	return SubscribeAuthCode_SUBSCRIBE_AUTH_CODE_UNSPECIFIED
}

func (x *SignSubscriptionTokenResponse) GetHmac() string {
	if x != nil {
		return x.Hmac
	}
	return ""
}

func (x *SignSubscriptionTokenResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *SignSubscriptionTokenResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SignSubscriptionTokenResponse) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x17gateway.controlplane.v1\"\xac\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12C\n" +
	"\bservices\x18\x02 \x03(\v2'.gateway.controlplane.v1.ServiceBindingR\bservices\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\"\xcd\x02\n" +
	"\x0eServiceBinding\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12.\n" +
	"\x13file_descriptor_set\x18\x02 \x01(\fR\x11fileDescriptorSet\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12!\n" +
	"\fopenapi_spec\x18\x05 \x01(\fR\vopenapiSpec\x12)\n" +
	"\x10graphql_endpoint\x18\x06 \x01(\tR\x0fgraphqlEndpoint\x12'\n" +
	"\x0fmax_concurrency\x18\a \x01(\rR\x0emaxConcurrency\x12?\n" +
	"\x1cmax_concurrency_per_instance\x18\b \x01(\rR\x19maxConcurrencyPerInstance\"\\\n" +
	"\x10RegisterResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\rR\n" +
	"ttlSeconds\";\n" +
	"\x10HeartbeatRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"<\n" +
	"\x11DeregisterRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\"\x14\n" +
	"\x12DeregisterResponse\"\x1a\n" +
	"\x18ListRegistrationsRequest\"h\n" +
	"\x19ListRegistrationsResponse\x12K\n" +
	"\rregistrations\x18\x01 \x03(\v2%.gateway.controlplane.v1.RegistrationR\rregistrations\"\xe2\x01\n" +
	"\fRegistration\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\rR\n" +
	"ttlSeconds\x123\n" +
	"\x16last_heartbeat_unix_ms\x18\x05 \x01(\x04R\x13lastHeartbeatUnixMs\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x06 \x03(\tR\n" +
	"namespaces\"\x12\n" +
	"\x10ListPeersRequest\"H\n" +
	"\x11ListPeersResponse\x123\n" +
	"\x05peers\x18\x01 \x03(\v2\x1d.gateway.controlplane.v1.PeerR\x05peers\"Y\n" +
	"\x04Peer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0ejoined_unix_ms\x18\x03 \x01(\x03R\fjoinedUnixMs\",\n" +
	"\x11ForgetPeerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"Q\n" +
	"\x12ForgetPeerResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\x12!\n" +
	"\fnew_replicas\x18\x02 \x01(\rR\vnewReplicas\"\x15\n" +
	"\x13ListServicesRequest\"\x82\x02\n" +
	"\x14ListServicesResponse\x12@\n" +
	"\bservices\x18\x01 \x03(\v2$.gateway.controlplane.v1.ServiceInfoR\bservices\x12X\n" +
	"\tstable_vn\x18\x03 \x03(\v2;.gateway.controlplane.v1.ListServicesResponse.StableVnEntryR\bstableVn\x1a;\n" +
	"\rStableVnEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01J\x04\b\x02\x10\x03R\venvironment\"\x85\x01\n" +
	"\vServiceInfo\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bhash_hex\x18\x03 \x01(\tR\ahashHex\x12#\n" +
	"\rreplica_count\x18\x04 \x01(\rR\freplicaCount\"k\n" +
	"\x1cSignSubscriptionTokenRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\"R\n" +
	"\x14RetractStableRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1c\n" +
	"\n" +
	"target_v_n\x18\x02 \x01(\rR\btargetVN\"K\n" +
	"\x15RetractStableResponse\x12\x1a\n" +
	"\tprior_v_n\x18\x01 \x01(\rR\apriorVN\x12\x16\n" +
	"\anew_v_n\x18\x02 \x01(\rR\x05newVN\"\xc4\x01\n" +
	"\x1dSignSubscriptionTokenResponse\x12>\n" +
	"\x04code\x18\x01 \x01(\x0e2*.gateway.controlplane.v1.SubscribeAuthCodeR\x04code\x12\x12\n" +
	"\x04hmac\x18\x02 \x01(\tR\x04hmac\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x10\n" +
	"\x03kid\x18\x05 \x01(\tR\x03kid*\xf7\x02\n" +
	"\x11SubscribeAuthCode\x12#\n" +
	"\x1fSUBSCRIBE_AUTH_CODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SUBSCRIBE_AUTH_CODE_OK\x10\x01\x12\x1f\n" +
	"\x1bSUBSCRIBE_AUTH_CODE_TOO_OLD\x10\x02\x12\x1f\n" +
	"\x1bSUBSCRIBE_AUTH_CODE_TOO_NEW\x10\x03\x12*\n" +
	"&SUBSCRIBE_AUTH_CODE_SIGNATURE_MISMATCH\x10\x04\x12!\n" +
	"\x1dSUBSCRIBE_AUTH_CODE_MALFORMED\x10\x05\x12#\n" +
	"\x1fSUBSCRIBE_AUTH_CODE_UNKNOWN_KID\x10\x06\x12\x1e\n" +
	"\x1aSUBSCRIBE_AUTH_CODE_DENIED\x10\a\x12#\n" +
	"\x1fSUBSCRIBE_AUTH_CODE_UNAVAILABLE\x10\b\x12&\n" +
	"\"SUBSCRIBE_AUTH_CODE_NOT_CONFIGURED\x10\t2\xe7\a\n" +
	"\fControlPlane\x12_\n" +
	"\bRegister\x12(.gateway.controlplane.v1.RegisterRequest\x1a).gateway.controlplane.v1.RegisterResponse\x12b\n" +
	"\tHeartbeat\x12).gateway.controlplane.v1.HeartbeatRequest\x1a*.gateway.controlplane.v1.HeartbeatResponse\x12e\n" +
	"\n" +
	"Deregister\x12*.gateway.controlplane.v1.DeregisterRequest\x1a+.gateway.controlplane.v1.DeregisterResponse\x12z\n" +
	"\x11ListRegistrations\x121.gateway.controlplane.v1.ListRegistrationsRequest\x1a2.gateway.controlplane.v1.ListRegistrationsResponse\x12b\n" +
	"\tListPeers\x12).gateway.controlplane.v1.ListPeersRequest\x1a*.gateway.controlplane.v1.ListPeersResponse\x12e\n" +
	"\n" +
	"ForgetPeer\x12*.gateway.controlplane.v1.ForgetPeerRequest\x1a+.gateway.controlplane.v1.ForgetPeerResponse\x12k\n" +
	"\fListServices\x12,.gateway.controlplane.v1.ListServicesRequest\x1a-.gateway.controlplane.v1.ListServicesResponse\x12\x86\x01\n" +
	"\x15SignSubscriptionToken\x125.gateway.controlplane.v1.SignSubscriptionTokenRequest\x1a6.gateway.controlplane.v1.SignSubscriptionTokenResponse\x12n\n" +
	"\rRetractStable\x12-.gateway.controlplane.v1.RetractStableRequest\x1a..gateway.controlplane.v1.RetractStableResponseBOZMgithub.com/iodesystems/go-api-gateway/gw/proto/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_control_proto_goTypes = []any{
	(SubscribeAuthCode)(0),                // 0: gateway.controlplane.v1.SubscribeAuthCode
	(*RegisterRequest)(nil),               // 1: gateway.controlplane.v1.RegisterRequest
	(*ServiceBinding)(nil),                // 2: gateway.controlplane.v1.ServiceBinding
	(*RegisterResponse)(nil),              // 3: gateway.controlplane.v1.RegisterResponse
	(*HeartbeatRequest)(nil),              // 4: gateway.controlplane.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 5: gateway.controlplane.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),             // 6: gateway.controlplane.v1.DeregisterRequest
	(*DeregisterResponse)(nil),            // 7: gateway.controlplane.v1.DeregisterResponse
	(*ListRegistrationsRequest)(nil),      // 8: gateway.controlplane.v1.ListRegistrationsRequest
	(*ListRegistrationsResponse)(nil),     // 9: gateway.controlplane.v1.ListRegistrationsResponse
	(*Registration)(nil),                  // 10: gateway.controlplane.v1.Registration
	(*ListPeersRequest)(nil),              // 11: gateway.controlplane.v1.ListPeersRequest
	(*ListPeersResponse)(nil),             // 12: gateway.controlplane.v1.ListPeersResponse
	(*Peer)(nil),                          // 13: gateway.controlplane.v1.Peer
	(*ForgetPeerRequest)(nil),             // 14: gateway.controlplane.v1.ForgetPeerRequest
	(*ForgetPeerResponse)(nil),            // 15: gateway.controlplane.v1.ForgetPeerResponse
	(*ListServicesRequest)(nil),           // 16: gateway.controlplane.v1.ListServicesRequest
	(*ListServicesResponse)(nil),          // 17: gateway.controlplane.v1.ListServicesResponse
	(*ServiceInfo)(nil),                   // 18: gateway.controlplane.v1.ServiceInfo
	(*SignSubscriptionTokenRequest)(nil),  // 19: gateway.controlplane.v1.SignSubscriptionTokenRequest
	(*RetractStableRequest)(nil),          // 20: gateway.controlplane.v1.RetractStableRequest
	(*RetractStableResponse)(nil),         // 21: gateway.controlplane.v1.RetractStableResponse
	(*SignSubscriptionTokenResponse)(nil), // 22: gateway.controlplane.v1.SignSubscriptionTokenResponse
	nil,                                   // 23: gateway.controlplane.v1.ListServicesResponse.StableVnEntry
}
var file_control_proto_depIdxs = []int32{
	2,  // 0: gateway.controlplane.v1.RegisterRequest.services:type_name -> gateway.controlplane.v1.ServiceBinding
	10, // 1: gateway.controlplane.v1.ListRegistrationsResponse.registrations:type_name -> gateway.controlplane.v1.Registration
	13, // 2: gateway.controlplane.v1.ListPeersResponse.peers:type_name -> gateway.controlplane.v1.Peer
	18, // 3: gateway.controlplane.v1.ListServicesResponse.services:type_name -> gateway.controlplane.v1.ServiceInfo
	23, // 4: gateway.controlplane.v1.ListServicesResponse.stable_vn:type_name -> gateway.controlplane.v1.ListServicesResponse.StableVnEntry
	0,  // 5: gateway.controlplane.v1.SignSubscriptionTokenResponse.code:type_name -> gateway.controlplane.v1.SubscribeAuthCode
	1,  // 6: gateway.controlplane.v1.ControlPlane.Register:input_type -> gateway.controlplane.v1.RegisterRequest
	4,  // 7: gateway.controlplane.v1.ControlPlane.Heartbeat:input_type -> gateway.controlplane.v1.HeartbeatRequest
	6,  // 8: gateway.controlplane.v1.ControlPlane.Deregister:input_type -> gateway.controlplane.v1.DeregisterRequest
	8,  // 9: gateway.controlplane.v1.ControlPlane.ListRegistrations:input_type -> gateway.controlplane.v1.ListRegistrationsRequest
	11, // 10: gateway.controlplane.v1.ControlPlane.ListPeers:input_type -> gateway.controlplane.v1.ListPeersRequest
	14, // 11: gateway.controlplane.v1.ControlPlane.ForgetPeer:input_type -> gateway.controlplane.v1.ForgetPeerRequest
	16, // 12: gateway.controlplane.v1.ControlPlane.ListServices:input_type -> gateway.controlplane.v1.ListServicesRequest
	19, // 13: gateway.controlplane.v1.ControlPlane.SignSubscriptionToken:input_type -> gateway.controlplane.v1.SignSubscriptionTokenRequest
	20, // 14: gateway.controlplane.v1.ControlPlane.RetractStable:input_type -> gateway.controlplane.v1.RetractStableRequest
	3,  // 15: gateway.controlplane.v1.ControlPlane.Register:output_type -> gateway.controlplane.v1.RegisterResponse
	5,  // 16: gateway.controlplane.v1.ControlPlane.Heartbeat:output_type -> gateway.controlplane.v1.HeartbeatResponse
	7,  // 17: gateway.controlplane.v1.ControlPlane.Deregister:output_type -> gateway.controlplane.v1.DeregisterResponse
	9,  // 18: gateway.controlplane.v1.ControlPlane.ListRegistrations:output_type -> gateway.controlplane.v1.ListRegistrationsResponse
	12, // 19: gateway.controlplane.v1.ControlPlane.ListPeers:output_type -> gateway.controlplane.v1.ListPeersResponse
	15, // 20: gateway.controlplane.v1.ControlPlane.ForgetPeer:output_type -> gateway.controlplane.v1.ForgetPeerResponse
	17, // 21: gateway.controlplane.v1.ControlPlane.ListServices:output_type -> gateway.controlplane.v1.ListServicesResponse
	22, // 22: gateway.controlplane.v1.ControlPlane.SignSubscriptionToken:output_type -> gateway.controlplane.v1.SignSubscriptionTokenResponse
	21, // 23: gateway.controlplane.v1.ControlPlane.RetractStable:output_type -> gateway.controlplane.v1.RetractStableResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
