// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/adminauth/v1/adminauth.proto

package adminauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminAuthCode int32

const (
	AdminAuthCode_ADMIN_AUTH_CODE_UNSPECIFIED AdminAuthCode = 0
	// Delegate authorized the request. The middleware accepts without
	// checking the boot token.
	AdminAuthCode_ADMIN_AUTH_CODE_OK AdminAuthCode = 1
	// Delegate explicitly rejected. The middleware returns 401 without
	// falling through to the boot token.
	AdminAuthCode_ADMIN_AUTH_CODE_DENIED AdminAuthCode = 2
	// Delegate is currently unavailable (degraded backend, exceeded
	// budget, etc.). Middleware falls through to boot-token check.
	AdminAuthCode_ADMIN_AUTH_CODE_UNAVAILABLE AdminAuthCode = 3
	// Delegate is registered but unwilling to make a decision (e.g.
	// policy not loaded). Middleware falls through to boot-token.
	AdminAuthCode_ADMIN_AUTH_CODE_NOT_CONFIGURED AdminAuthCode = 4
)

// Enum value maps for AdminAuthCode.
var (
	AdminAuthCode_name = map[int32]string{
		0: "ADMIN_AUTH_CODE_UNSPECIFIED",
		1: "ADMIN_AUTH_CODE_OK",
		2: "ADMIN_AUTH_CODE_DENIED",
		3: "ADMIN_AUTH_CODE_UNAVAILABLE",
		4: "ADMIN_AUTH_CODE_NOT_CONFIGURED",
	}
	AdminAuthCode_value = map[string]int32{
		"ADMIN_AUTH_CODE_UNSPECIFIED":    0,
		"ADMIN_AUTH_CODE_OK":             1,
		"ADMIN_AUTH_CODE_DENIED":         2,
		"ADMIN_AUTH_CODE_UNAVAILABLE":    3,
		"ADMIN_AUTH_CODE_NOT_CONFIGURED": 4,
	}
)

func (x AdminAuthCode) Enum() *AdminAuthCode {
	p := new(AdminAuthCode)
	*p = x
	return p
}

func (x AdminAuthCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminAuthCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_proto_adminauth_v1_adminauth_proto_enumTypes[0].Descriptor()
}

func (AdminAuthCode) Type() protoreflect.EnumType {
	return &file_gw_proto_adminauth_v1_adminauth_proto_enumTypes[0]
}

func (x AdminAuthCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminAuthCode.Descriptor instead.
func (AdminAuthCode) EnumDescriptor() ([]byte, []int) {
	return file_gw_proto_adminauth_v1_adminauth_proto_rawDescGZIP(), []int{0}
}

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bearer token presented by the client (the raw value after
	// `Bearer `). Empty string when the request had no Authorization
	// header — the delegate decides whether to accept anonymous calls.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// HTTP method, uppercased (POST/PUT/PATCH/DELETE/...).
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Request path on the gateway (e.g. "/admin/peers/X/forget").
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Inbound remote address (best-effort; may be empty if the gateway
	// is behind a proxy that doesn't forward it).
	RemoteAddr    string `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_gw_proto_adminauth_v1_adminauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_adminauth_v1_adminauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_adminauth_v1_adminauth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthorizeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthorizeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuthorizeRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  AdminAuthCode          `protobuf:"varint,1,opt,name=code,proto3,enum=gateway.adminauth.v1.AdminAuthCode" json:"code,omitempty"`
	// Optional, for operator logs. Never leaked to clients.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_gw_proto_adminauth_v1_adminauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_adminauth_v1_adminauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_gw_proto_adminauth_v1_adminauth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetCode() AdminAuthCode {
	if x != nil {
		return x.Code
	}
	return AdminAuthCode_ADMIN_AUTH_CODE_UNSPECIFIED
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gw_proto_adminauth_v1_adminauth_proto protoreflect.FileDescriptor

const file_gw_proto_adminauth_v1_adminauth_proto_rawDesc = "" +
	"\n" +
	"%gw/proto/adminauth/v1/adminauth.proto\x12\x14gateway.adminauth.v1\"u\n" +
	"\x10AuthorizeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vremote_addr\x18\x04 \x01(\tR\n" +
	"remoteAddr\"d\n" +
	"\x11AuthorizeResponse\x127\n" +
	"\x04code\x18\x01 \x01(\x0e2#.gateway.adminauth.v1.AdminAuthCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\xa9\x01\n" +
	"\rAdminAuthCode\x12\x1f\n" +
	"\x1bADMIN_AUTH_CODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ADMIN_AUTH_CODE_OK\x10\x01\x12\x1a\n" +
	"\x16ADMIN_AUTH_CODE_DENIED\x10\x02\x12\x1f\n" +
	"\x1bADMIN_AUTH_CODE_UNAVAILABLE\x10\x03\x12\"\n" +
	"\x1eADMIN_AUTH_CODE_NOT_CONFIGURED\x10\x042o\n" +
	"\x0fAdminAuthorizer\x12\\\n" +
	"\tAuthorize\x12&.gateway.adminauth.v1.AuthorizeRequest\x1a'.gateway.adminauth.v1.AuthorizeResponseB?Z=github.com/iodesystems/gwag/gw/proto/adminauth/v1;adminauthv1b\x06proto3"

var (
	file_gw_proto_adminauth_v1_adminauth_proto_rawDescOnce sync.Once
	file_gw_proto_adminauth_v1_adminauth_proto_rawDescData []byte
)

func file_gw_proto_adminauth_v1_adminauth_proto_rawDescGZIP() []byte {
	file_gw_proto_adminauth_v1_adminauth_proto_rawDescOnce.Do(func() {
		file_gw_proto_adminauth_v1_adminauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_adminauth_v1_adminauth_proto_rawDesc), len(file_gw_proto_adminauth_v1_adminauth_proto_rawDesc)))
	})
	return file_gw_proto_adminauth_v1_adminauth_proto_rawDescData
}

var file_gw_proto_adminauth_v1_adminauth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gw_proto_adminauth_v1_adminauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gw_proto_adminauth_v1_adminauth_proto_goTypes = []any{
	(AdminAuthCode)(0),        // 0: gateway.adminauth.v1.AdminAuthCode
	(*AuthorizeRequest)(nil),  // 1: gateway.adminauth.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 2: gateway.adminauth.v1.AuthorizeResponse
}
var file_gw_proto_adminauth_v1_adminauth_proto_depIdxs = []int32{
	0, // 0: gateway.adminauth.v1.AuthorizeResponse.code:type_name -> gateway.adminauth.v1.AdminAuthCode
	1, // 1: gateway.adminauth.v1.AdminAuthorizer.Authorize:input_type -> gateway.adminauth.v1.AuthorizeRequest
	2, // 2: gateway.adminauth.v1.AdminAuthorizer.Authorize:output_type -> gateway.adminauth.v1.AuthorizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gw_proto_adminauth_v1_adminauth_proto_init() }
func file_gw_proto_adminauth_v1_adminauth_proto_init() {
	if File_gw_proto_adminauth_v1_adminauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_adminauth_v1_adminauth_proto_rawDesc), len(file_gw_proto_adminauth_v1_adminauth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_adminauth_v1_adminauth_proto_goTypes,
		DependencyIndexes: file_gw_proto_adminauth_v1_adminauth_proto_depIdxs,
		EnumInfos:         file_gw_proto_adminauth_v1_adminauth_proto_enumTypes,
		MessageInfos:      file_gw_proto_adminauth_v1_adminauth_proto_msgTypes,
	}.Build()
	File_gw_proto_adminauth_v1_adminauth_proto = out.File
	file_gw_proto_adminauth_v1_adminauth_proto_goTypes = nil
	file_gw_proto_adminauth_v1_adminauth_proto_depIdxs = nil
}
