// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: adminevents/v1/adminevents.proto

package admineventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceChange_Action int32

const (
	ServiceChange_ACTION_UNSPECIFIED  ServiceChange_Action = 0
	ServiceChange_ACTION_REGISTERED   ServiceChange_Action = 1 // new replica joined a pool
	ServiceChange_ACTION_DEREGISTERED ServiceChange_Action = 2 // replica left a pool (or pool destroyed)
)

// Enum value maps for ServiceChange_Action.
var (
	ServiceChange_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_REGISTERED",
		2: "ACTION_DEREGISTERED",
	}
	ServiceChange_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":  0,
		"ACTION_REGISTERED":   1,
		"ACTION_DEREGISTERED": 2,
	}
)

func (x ServiceChange_Action) Enum() *ServiceChange_Action {
	p := new(ServiceChange_Action)
	*p = x
	return p
}

func (x ServiceChange_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceChange_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_adminevents_v1_adminevents_proto_enumTypes[0].Descriptor()
}

func (ServiceChange_Action) Type() protoreflect.EnumType {
	return &file_adminevents_v1_adminevents_proto_enumTypes[0]
}

func (x ServiceChange_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceChange_Action.Descriptor instead.
func (ServiceChange_Action) EnumDescriptor() ([]byte, []int) {
	return file_adminevents_v1_adminevents_proto_rawDescGZIP(), []int{1, 0}
}

type WatchServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filter to a single namespace; empty / unset → all namespaces.
	// Translates into NATS subject component (so client-side wildcard
	// matching is just NATS subject hierarchy).
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *WatchServicesRequest) Reset() {
	*x = WatchServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminevents_v1_adminevents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchServicesRequest) ProtoMessage() {}

func (x *WatchServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminevents_v1_adminevents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchServicesRequest.ProtoReflect.Descriptor instead.
func (*WatchServicesRequest) Descriptor() ([]byte, []int) {
	return file_adminevents_v1_adminevents_proto_rawDescGZIP(), []int{0}
}

func (x *WatchServicesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ServiceChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action    ServiceChange_Action `protobuf:"varint,1,opt,name=action,proto3,enum=gateway.adminevents.v1.ServiceChange_Action" json:"action,omitempty"`
	Namespace string               `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version   string               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Addr      string               `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	// Wall-clock timestamp the gateway applied the change.
	TimestampUnixMs int64 `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// Pool replica count after the change (0 when the pool was
	// destroyed entirely).
	ReplicaCount uint32 `protobuf:"varint,6,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
}

func (x *ServiceChange) Reset() {
	*x = ServiceChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminevents_v1_adminevents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChange) ProtoMessage() {}

func (x *ServiceChange) ProtoReflect() protoreflect.Message {
	mi := &file_adminevents_v1_adminevents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChange.ProtoReflect.Descriptor instead.
func (*ServiceChange) Descriptor() ([]byte, []int) {
	return file_adminevents_v1_adminevents_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceChange) GetAction() ServiceChange_Action {
	if x != nil {
		return x.Action
	}
	return ServiceChange_ACTION_UNSPECIFIED
}

func (x *ServiceChange) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceChange) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceChange) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServiceChange) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ServiceChange) GetReplicaCount() uint32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

var File_adminevents_v1_adminevents_proto protoreflect.FileDescriptor

var file_adminevents_v1_adminevents_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x16, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x34, 0x0a, 0x14, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0xc4, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x50, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x12, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x17,
	0x0a, 0x13, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x52, 0x45, 0x47, 0x49, 0x53,
	0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x02, 0x32, 0x75, 0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x66, 0x0a, 0x0d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x30, 0x01, 0x42, 0x44,
	0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6f, 0x64,
	0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2d,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adminevents_v1_adminevents_proto_rawDescOnce sync.Once
	file_adminevents_v1_adminevents_proto_rawDescData = file_adminevents_v1_adminevents_proto_rawDesc
)

func file_adminevents_v1_adminevents_proto_rawDescGZIP() []byte {
	file_adminevents_v1_adminevents_proto_rawDescOnce.Do(func() {
		file_adminevents_v1_adminevents_proto_rawDescData = protoimpl.X.CompressGZIP(file_adminevents_v1_adminevents_proto_rawDescData)
	})
	return file_adminevents_v1_adminevents_proto_rawDescData
}

var file_adminevents_v1_adminevents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_adminevents_v1_adminevents_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adminevents_v1_adminevents_proto_goTypes = []interface{}{
	(ServiceChange_Action)(0),    // 0: gateway.adminevents.v1.ServiceChange.Action
	(*WatchServicesRequest)(nil), // 1: gateway.adminevents.v1.WatchServicesRequest
	(*ServiceChange)(nil),        // 2: gateway.adminevents.v1.ServiceChange
}
var file_adminevents_v1_adminevents_proto_depIdxs = []int32{
	0, // 0: gateway.adminevents.v1.ServiceChange.action:type_name -> gateway.adminevents.v1.ServiceChange.Action
	1, // 1: gateway.adminevents.v1.AdminEvents.WatchServices:input_type -> gateway.adminevents.v1.WatchServicesRequest
	2, // 2: gateway.adminevents.v1.AdminEvents.WatchServices:output_type -> gateway.adminevents.v1.ServiceChange
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_adminevents_v1_adminevents_proto_init() }
func file_adminevents_v1_adminevents_proto_init() {
	if File_adminevents_v1_adminevents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adminevents_v1_adminevents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminevents_v1_adminevents_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adminevents_v1_adminevents_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adminevents_v1_adminevents_proto_goTypes,
		DependencyIndexes: file_adminevents_v1_adminevents_proto_depIdxs,
		EnumInfos:         file_adminevents_v1_adminevents_proto_enumTypes,
		MessageInfos:      file_adminevents_v1_adminevents_proto_msgTypes,
	}.Build()
	File_adminevents_v1_adminevents_proto = out.File
	file_adminevents_v1_adminevents_proto_rawDesc = nil
	file_adminevents_v1_adminevents_proto_goTypes = nil
	file_adminevents_v1_adminevents_proto_depIdxs = nil
}
