// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: adminevents/v1/adminevents.proto

package admineventsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminEvents_WatchServices_FullMethodName = "/gateway.adminevents.v1.AdminEvents/WatchServices"
)

// AdminEventsClient is the client API for AdminEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminEvents exposes gateway-internal admin events as a
// server-streaming RPC. Subscriptions are NATS-backed (per the
// project's transport decision); the gateway publishes to
// `events.admin_events.WatchServices.<namespace>` whenever its
// service registry mutates, and clients consume via the auto-
// generated `admin_events_watchServices` Subscription field.
//
// Register via `Gateway.AddAdminEvents()` — the gateway is the
// publisher, and there is no separate gRPC implementation (the
// stream dispatch is intentionally never invoked).
type AdminEventsClient interface {
	// WatchServices yields a ServiceChange every time a registry
	// entry is added, removed, or replaced. Optional namespace
	// filter selects a single namespace; empty matches all.
	WatchServices(ctx context.Context, in *WatchServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceChange], error)
}

type adminEventsClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminEventsClient(cc grpc.ClientConnInterface) AdminEventsClient {
	return &adminEventsClient{cc}
}

func (c *adminEventsClient) WatchServices(ctx context.Context, in *WatchServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceChange], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminEvents_ServiceDesc.Streams[0], AdminEvents_WatchServices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchServicesRequest, ServiceChange]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminEvents_WatchServicesClient = grpc.ServerStreamingClient[ServiceChange]

// AdminEventsServer is the server API for AdminEvents service.
// All implementations must embed UnimplementedAdminEventsServer
// for forward compatibility.
//
// AdminEvents exposes gateway-internal admin events as a
// server-streaming RPC. Subscriptions are NATS-backed (per the
// project's transport decision); the gateway publishes to
// `events.admin_events.WatchServices.<namespace>` whenever its
// service registry mutates, and clients consume via the auto-
// generated `admin_events_watchServices` Subscription field.
//
// Register via `Gateway.AddAdminEvents()` — the gateway is the
// publisher, and there is no separate gRPC implementation (the
// stream dispatch is intentionally never invoked).
type AdminEventsServer interface {
	// WatchServices yields a ServiceChange every time a registry
	// entry is added, removed, or replaced. Optional namespace
	// filter selects a single namespace; empty matches all.
	WatchServices(*WatchServicesRequest, grpc.ServerStreamingServer[ServiceChange]) error
	mustEmbedUnimplementedAdminEventsServer()
}

// UnimplementedAdminEventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminEventsServer struct{}

func (UnimplementedAdminEventsServer) WatchServices(*WatchServicesRequest, grpc.ServerStreamingServer[ServiceChange]) error {
	return status.Error(codes.Unimplemented, "method WatchServices not implemented")
}
func (UnimplementedAdminEventsServer) mustEmbedUnimplementedAdminEventsServer() {}
func (UnimplementedAdminEventsServer) testEmbeddedByValue()                     {}

// UnsafeAdminEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminEventsServer will
// result in compilation errors.
type UnsafeAdminEventsServer interface {
	mustEmbedUnimplementedAdminEventsServer()
}

func RegisterAdminEventsServer(s grpc.ServiceRegistrar, srv AdminEventsServer) {
	// If the following call panics, it indicates UnimplementedAdminEventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminEvents_ServiceDesc, srv)
}

func _AdminEvents_WatchServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchServicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminEventsServer).WatchServices(m, &grpc.GenericServerStream[WatchServicesRequest, ServiceChange]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminEvents_WatchServicesServer = grpc.ServerStreamingServer[ServiceChange]

// AdminEvents_ServiceDesc is the grpc.ServiceDesc for AdminEvents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.adminevents.v1.AdminEvents",
	HandlerType: (*AdminEventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchServices",
			Handler:       _AdminEvents_WatchServices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "adminevents/v1/adminevents.proto",
}
