// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/upload/v1/options.proto

package uploadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_gw_proto_upload_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51235,
		Name:          "gwag.upload.v1.upload",
		Tag:           "varint,51235,opt,name=upload",
		Filename:      "gw/proto/upload/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Marks a `bytes` field as accepting a graphql `Upload!` value.
	// The gateway exposes the field as an `Upload!` arg in the
	// generated GraphQL schema; the dispatcher reads the upload body
	// (inline multipart or tus-staged) into the field, capped by the
	// gateway's `WithUploadLimit`. Only valid on `bytes` fields —
	// ingest ignores the option on every other kind.
	//
	// Custom-option number 51235 is in the descriptor.proto in-house
	// 50000–99999 range; gateway-internal so the in-house range is
	// correct (per descriptor.proto guidance).
	//
	// optional bool upload = 51235;
	E_Upload = &file_gw_proto_upload_v1_options_proto_extTypes[0]
)

var File_gw_proto_upload_v1_options_proto protoreflect.FileDescriptor

const file_gw_proto_upload_v1_options_proto_rawDesc = "" +
	"\n" +
	" gw/proto/upload/v1/options.proto\x12\x0egwag.upload.v1\x1a google/protobuf/descriptor.proto::\n" +
	"\x06upload\x12\x1d.google.protobuf.FieldOptions\x18\xa3\x90\x03 \x01(\bR\x06upload\x88\x01\x01B9Z7github.com/iodesystems/gwag/gw/proto/upload/v1;uploadv1b\x06proto3"

var file_gw_proto_upload_v1_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_gw_proto_upload_v1_options_proto_depIdxs = []int32{
	0, // 0: gwag.upload.v1.upload:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gw_proto_upload_v1_options_proto_init() }
func file_gw_proto_upload_v1_options_proto_init() {
	if File_gw_proto_upload_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_upload_v1_options_proto_rawDesc), len(file_gw_proto_upload_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_gw_proto_upload_v1_options_proto_goTypes,
		DependencyIndexes: file_gw_proto_upload_v1_options_proto_depIdxs,
		ExtensionInfos:    file_gw_proto_upload_v1_options_proto_extTypes,
	}.Build()
	File_gw_proto_upload_v1_options_proto = out.File
	file_gw_proto_upload_v1_options_proto_goTypes = nil
	file_gw_proto_upload_v1_options_proto_depIdxs = nil
}
