package relay

import (
	"fmt"
	"reflect"
	"strings"
)

// ChannelSpec describes one live channel's payload for codegen.
type ChannelSpec struct {
	Name  string       // TS stem: "Drive" → DriveEvent
	Event reflect.Type // the Go payload struct
}

// EnumSpec maps a named Go string type to its closed value set — Go has no enum
// reflection, so the values are supplied explicitly and emitted as a TS union.
type EnumSpec struct {
	Name   string       // TS type name, e.g. "EventType"
	Type   reflect.Type // the Go named type the struct fields use
	Values []string
}

// GenerateTypes returns the TS source for the live event payload types: the
// enum unions + one object type per channel. It is deliberately schema-agnostic
// — no GraphQL/gat names, no transport — so the emitter is reusable across any
// relay adopter. Returns an error if a payload uses a shape it doesn't model
// (unsupported types fail the build loudly rather than emit something wrong).
func GenerateTypes(channels []ChannelSpec, enums []EnumSpec) (string, error) {
	byType := make(map[reflect.Type]EnumSpec, len(enums))
	for _, e := range enums {
		byType[e.Type] = e
	}

	var b strings.Builder
	b.WriteString("// Code generated by gnat-ws-relay; DO NOT EDIT.\n")
	b.WriteString("// Source of truth: the Go event structs in the adopter's channel registry.\n\n")

	for _, e := range enums {
		fmt.Fprintf(&b, "export type %s = %s\n\n", e.Name, tsUnion(e.Values))
	}
	for _, ch := range channels {
		obj, err := tsObject(ch.Event, byType)
		if err != nil {
			return "", fmt.Errorf("channel %q: %w", ch.Name, err)
		}
		fmt.Fprintf(&b, "export type %sEvent = %s\n\n", ch.Name, obj)
	}
	return b.String(), nil
}

func tsObject(t reflect.Type, enums map[reflect.Type]EnumSpec) (string, error) {
	if t.Kind() != reflect.Struct {
		return "", fmt.Errorf("expected struct, got %s", t.Kind())
	}
	var lines []string
	for _, f := range reflect.VisibleFields(t) {
		if !f.IsExported() {
			continue
		}
		name, opts := jsonField(f)
		if name == "-" {
			continue
		}
		ts, err := tsType(f.Type, opts["string"], enums)
		if err != nil {
			return "", fmt.Errorf("field %s: %w", f.Name, err)
		}
		if opts["omitempty"] {
			ts += " | null"
		}
		lines = append(lines, "  "+name+": "+ts)
	}
	return "{\n" + strings.Join(lines, "\n") + "\n}", nil
}

func tsType(t reflect.Type, asString bool, enums map[reflect.Type]EnumSpec) (string, error) {
	if e, ok := enums[t]; ok {
		return e.Name, nil
	}
	switch t.Kind() {
	case reflect.String:
		return "string", nil
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		// int64 tagged json:",string" (an always-string-id contract) → string.
		if asString {
			return "string", nil
		}
		return "number", nil
	case reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.Pointer:
		inner, err := tsType(t.Elem(), asString, enums)
		if err != nil {
			return "", err
		}
		return inner + " | null", nil
	case reflect.Slice:
		inner, err := tsType(t.Elem(), false, enums)
		if err != nil {
			return "", err
		}
		return inner + "[]", nil
	case reflect.Struct:
		return tsObject(t, enums)
	default:
		return "", fmt.Errorf("unsupported kind %s", t.Kind())
	}
}

func tsUnion(values []string) string {
	if len(values) == 0 {
		return "never"
	}
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = "'" + v + "'"
	}
	return strings.Join(parts, " | ")
}

// jsonField returns a field's JSON name and option set (string, omitempty). An
// empty json tag falls back to the Go field name.
func jsonField(f reflect.StructField) (string, map[string]bool) {
	opts := map[string]bool{}
	tag := f.Tag.Get("json")
	if tag == "" {
		return f.Name, opts
	}
	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		name = f.Name
	}
	for _, o := range parts[1:] {
		opts[o] = true
	}
	return name, opts
}
