// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gw/proto/pubsubauth/v1/pubsubauth.proto

package pubsubauthv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PubSubAuthorizer_Authorize_FullMethodName = "/gateway.pubsubauth.v1.PubSubAuthorizer/Authorize"
)

// PubSubAuthorizerClient is the client API for PubSubAuthorizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PubSubAuthorizer is the optional delegate the gateway calls when a
// pub/sub channel is governed by tier `delegate+hmac`
// (WithChannelAuth(..., ChannelAuthDelegate)). HMAC is verified first;
// only after it passes does the delegate get the final say.
//
// Register an implementation under namespace "_pubsub_auth" / version
// v1. Policy mirrors AdminAuthorizer: OK accepts, DENIED rejects
// without falling through. Anything else (UNAVAILABLE, NOT_CONFIGURED,
// UNSPECIFIED, transport error) falls through to HMAC-only — the
// always-works posture stays the floor when the delegate is sick.
type PubSubAuthorizerClient interface {
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
}

type pubSubAuthorizerClient struct {
	cc grpc.ClientConnInterface
}

func NewPubSubAuthorizerClient(cc grpc.ClientConnInterface) PubSubAuthorizerClient {
	return &pubSubAuthorizerClient{cc}
}

func (c *pubSubAuthorizerClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, PubSubAuthorizer_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubSubAuthorizerServer is the server API for PubSubAuthorizer service.
// All implementations must embed UnimplementedPubSubAuthorizerServer
// for forward compatibility.
//
// PubSubAuthorizer is the optional delegate the gateway calls when a
// pub/sub channel is governed by tier `delegate+hmac`
// (WithChannelAuth(..., ChannelAuthDelegate)). HMAC is verified first;
// only after it passes does the delegate get the final say.
//
// Register an implementation under namespace "_pubsub_auth" / version
// v1. Policy mirrors AdminAuthorizer: OK accepts, DENIED rejects
// without falling through. Anything else (UNAVAILABLE, NOT_CONFIGURED,
// UNSPECIFIED, transport error) falls through to HMAC-only — the
// always-works posture stays the floor when the delegate is sick.
type PubSubAuthorizerServer interface {
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	mustEmbedUnimplementedPubSubAuthorizerServer()
}

// UnimplementedPubSubAuthorizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPubSubAuthorizerServer struct{}

func (UnimplementedPubSubAuthorizerServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedPubSubAuthorizerServer) mustEmbedUnimplementedPubSubAuthorizerServer() {}
func (UnimplementedPubSubAuthorizerServer) testEmbeddedByValue()                          {}

// UnsafePubSubAuthorizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubSubAuthorizerServer will
// result in compilation errors.
type UnsafePubSubAuthorizerServer interface {
	mustEmbedUnimplementedPubSubAuthorizerServer()
}

func RegisterPubSubAuthorizerServer(s grpc.ServiceRegistrar, srv PubSubAuthorizerServer) {
	// If the following call panics, it indicates UnimplementedPubSubAuthorizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PubSubAuthorizer_ServiceDesc, srv)
}

func _PubSubAuthorizer_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubAuthorizerServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubAuthorizer_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubAuthorizerServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PubSubAuthorizer_ServiceDesc is the grpc.ServiceDesc for PubSubAuthorizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubSubAuthorizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.pubsubauth.v1.PubSubAuthorizer",
	HandlerType: (*PubSubAuthorizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _PubSubAuthorizer_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gw/proto/pubsubauth/v1/pubsubauth.proto",
}
