// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/pubsubauth/v1/pubsubauth.proto

package pubsubauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubSubAuthCode int32

const (
	PubSubAuthCode_PUBSUB_AUTH_CODE_UNSPECIFIED PubSubAuthCode = 0
	// Delegate authorized the call. The gateway accepts.
	PubSubAuthCode_PUBSUB_AUTH_CODE_OK PubSubAuthCode = 1
	// Delegate explicitly rejected. The gateway returns an error to the
	// client without falling through to HMAC-only.
	PubSubAuthCode_PUBSUB_AUTH_CODE_DENIED PubSubAuthCode = 2
	// Delegate is currently unavailable (degraded backend, exceeded
	// budget, etc.). Gateway falls through to HMAC-only.
	PubSubAuthCode_PUBSUB_AUTH_CODE_UNAVAILABLE PubSubAuthCode = 3
	// Delegate is registered but unwilling to make a decision (e.g.
	// policy not loaded). Gateway falls through to HMAC-only.
	PubSubAuthCode_PUBSUB_AUTH_CODE_NOT_CONFIGURED PubSubAuthCode = 4
)

// Enum value maps for PubSubAuthCode.
var (
	PubSubAuthCode_name = map[int32]string{
		0: "PUBSUB_AUTH_CODE_UNSPECIFIED",
		1: "PUBSUB_AUTH_CODE_OK",
		2: "PUBSUB_AUTH_CODE_DENIED",
		3: "PUBSUB_AUTH_CODE_UNAVAILABLE",
		4: "PUBSUB_AUTH_CODE_NOT_CONFIGURED",
	}
	PubSubAuthCode_value = map[string]int32{
		"PUBSUB_AUTH_CODE_UNSPECIFIED":    0,
		"PUBSUB_AUTH_CODE_OK":             1,
		"PUBSUB_AUTH_CODE_DENIED":         2,
		"PUBSUB_AUTH_CODE_UNAVAILABLE":    3,
		"PUBSUB_AUTH_CODE_NOT_CONFIGURED": 4,
	}
)

func (x PubSubAuthCode) Enum() *PubSubAuthCode {
	p := new(PubSubAuthCode)
	*p = x
	return p
}

func (x PubSubAuthCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PubSubAuthCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_proto_pubsubauth_v1_pubsubauth_proto_enumTypes[0].Descriptor()
}

func (PubSubAuthCode) Type() protoreflect.EnumType {
	return &file_gw_proto_pubsubauth_v1_pubsubauth_proto_enumTypes[0]
}

func (x PubSubAuthCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PubSubAuthCode.Descriptor instead.
func (PubSubAuthCode) EnumDescriptor() ([]byte, []int) {
	return file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescGZIP(), []int{0}
}

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested channel string as the client sent it. Concrete
	// subject for Pub; may be a NATS-style wildcard pattern for Sub.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// The HMAC token presented by the client (base64), already verified
	// by the gateway before the delegate is called. Forwarded so the
	// delegate can correlate against its own token issuance records.
	Hmac string `protobuf:"bytes,2,opt,name=hmac,proto3" json:"hmac,omitempty"`
	// Timestamp (unix seconds) the HMAC was minted with. Forwarded for
	// the same correlation reason.
	Ts int64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// True when the call site is Subscription.ps.sub (channel may be a
	// wildcard); false when it's Mutation.ps.pub (channel is literal).
	Wildcard bool `protobuf:"varint,4,opt,name=wildcard,proto3" json:"wildcard,omitempty"`
	// Inbound remote address, best-effort. May be empty when the gateway
	// is behind a proxy that doesn't forward it.
	RemoteAddr    string `protobuf:"bytes,5,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_gw_proto_pubsubauth_v1_pubsubauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_pubsubauth_v1_pubsubauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AuthorizeRequest) GetHmac() string {
	if x != nil {
		return x.Hmac
	}
	return ""
}

func (x *AuthorizeRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *AuthorizeRequest) GetWildcard() bool {
	if x != nil {
		return x.Wildcard
	}
	return false
}

func (x *AuthorizeRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  PubSubAuthCode         `protobuf:"varint,1,opt,name=code,proto3,enum=gateway.pubsubauth.v1.PubSubAuthCode" json:"code,omitempty"`
	// Optional, for operator logs. Never leaked to clients.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_gw_proto_pubsubauth_v1_pubsubauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_pubsubauth_v1_pubsubauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetCode() PubSubAuthCode {
	if x != nil {
		return x.Code
	}
	return PubSubAuthCode_PUBSUB_AUTH_CODE_UNSPECIFIED
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gw_proto_pubsubauth_v1_pubsubauth_proto protoreflect.FileDescriptor

const file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDesc = "" +
	"\n" +
	"'gw/proto/pubsubauth/v1/pubsubauth.proto\x12\x15gateway.pubsubauth.v1\"\x8d\x01\n" +
	"\x10AuthorizeRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x12\n" +
	"\x04hmac\x18\x02 \x01(\tR\x04hmac\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x1a\n" +
	"\bwildcard\x18\x04 \x01(\bR\bwildcard\x12\x1f\n" +
	"\vremote_addr\x18\x05 \x01(\tR\n" +
	"remoteAddr\"f\n" +
	"\x11AuthorizeResponse\x129\n" +
	"\x04code\x18\x01 \x01(\x0e2%.gateway.pubsubauth.v1.PubSubAuthCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\xaf\x01\n" +
	"\x0ePubSubAuthCode\x12 \n" +
	"\x1cPUBSUB_AUTH_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PUBSUB_AUTH_CODE_OK\x10\x01\x12\x1b\n" +
	"\x17PUBSUB_AUTH_CODE_DENIED\x10\x02\x12 \n" +
	"\x1cPUBSUB_AUTH_CODE_UNAVAILABLE\x10\x03\x12#\n" +
	"\x1fPUBSUB_AUTH_CODE_NOT_CONFIGURED\x10\x042r\n" +
	"\x10PubSubAuthorizer\x12^\n" +
	"\tAuthorize\x12'.gateway.pubsubauth.v1.AuthorizeRequest\x1a(.gateway.pubsubauth.v1.AuthorizeResponseBAZ?github.com/iodesystems/gwag/gw/proto/pubsubauth/v1;pubsubauthv1b\x06proto3"

var (
	file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescOnce sync.Once
	file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescData []byte
)

func file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescGZIP() []byte {
	file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescOnce.Do(func() {
		file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDesc), len(file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDesc)))
	})
	return file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDescData
}

var file_gw_proto_pubsubauth_v1_pubsubauth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gw_proto_pubsubauth_v1_pubsubauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gw_proto_pubsubauth_v1_pubsubauth_proto_goTypes = []any{
	(PubSubAuthCode)(0),       // 0: gateway.pubsubauth.v1.PubSubAuthCode
	(*AuthorizeRequest)(nil),  // 1: gateway.pubsubauth.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 2: gateway.pubsubauth.v1.AuthorizeResponse
}
var file_gw_proto_pubsubauth_v1_pubsubauth_proto_depIdxs = []int32{
	0, // 0: gateway.pubsubauth.v1.AuthorizeResponse.code:type_name -> gateway.pubsubauth.v1.PubSubAuthCode
	1, // 1: gateway.pubsubauth.v1.PubSubAuthorizer.Authorize:input_type -> gateway.pubsubauth.v1.AuthorizeRequest
	2, // 2: gateway.pubsubauth.v1.PubSubAuthorizer.Authorize:output_type -> gateway.pubsubauth.v1.AuthorizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gw_proto_pubsubauth_v1_pubsubauth_proto_init() }
func file_gw_proto_pubsubauth_v1_pubsubauth_proto_init() {
	if File_gw_proto_pubsubauth_v1_pubsubauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDesc), len(file_gw_proto_pubsubauth_v1_pubsubauth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_pubsubauth_v1_pubsubauth_proto_goTypes,
		DependencyIndexes: file_gw_proto_pubsubauth_v1_pubsubauth_proto_depIdxs,
		EnumInfos:         file_gw_proto_pubsubauth_v1_pubsubauth_proto_enumTypes,
		MessageInfos:      file_gw_proto_pubsubauth_v1_pubsubauth_proto_msgTypes,
	}.Build()
	File_gw_proto_pubsubauth_v1_pubsubauth_proto = out.File
	file_gw_proto_pubsubauth_v1_pubsubauth_proto_goTypes = nil
	file_gw_proto_pubsubauth_v1_pubsubauth_proto_depIdxs = nil
}
