// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gw/proto/adminevents/v1/adminevents.proto

package admineventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceChange_Action int32

const (
	ServiceChange_ACTION_UNSPECIFIED  ServiceChange_Action = 0
	ServiceChange_ACTION_REGISTERED   ServiceChange_Action = 1 // new replica joined a pool
	ServiceChange_ACTION_DEREGISTERED ServiceChange_Action = 2 // replica left a pool (or pool destroyed)
)

// Enum value maps for ServiceChange_Action.
var (
	ServiceChange_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_REGISTERED",
		2: "ACTION_DEREGISTERED",
	}
	ServiceChange_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":  0,
		"ACTION_REGISTERED":   1,
		"ACTION_DEREGISTERED": 2,
	}
)

func (x ServiceChange_Action) Enum() *ServiceChange_Action {
	p := new(ServiceChange_Action)
	*p = x
	return p
}

func (x ServiceChange_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceChange_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_proto_adminevents_v1_adminevents_proto_enumTypes[0].Descriptor()
}

func (ServiceChange_Action) Type() protoreflect.EnumType {
	return &file_gw_proto_adminevents_v1_adminevents_proto_enumTypes[0]
}

func (x ServiceChange_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceChange_Action.Descriptor instead.
func (ServiceChange_Action) EnumDescriptor() ([]byte, []int) {
	return file_gw_proto_adminevents_v1_adminevents_proto_rawDescGZIP(), []int{1, 0}
}

type WatchServicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter to a single namespace; empty / unset → all namespaces.
	// Translates into NATS subject component (so client-side wildcard
	// matching is just NATS subject hierarchy).
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchServicesRequest) Reset() {
	*x = WatchServicesRequest{}
	mi := &file_gw_proto_adminevents_v1_adminevents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchServicesRequest) ProtoMessage() {}

func (x *WatchServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_adminevents_v1_adminevents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchServicesRequest.ProtoReflect.Descriptor instead.
func (*WatchServicesRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_adminevents_v1_adminevents_proto_rawDescGZIP(), []int{0}
}

func (x *WatchServicesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ServiceChange struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Action    ServiceChange_Action   `protobuf:"varint,1,opt,name=action,proto3,enum=gateway.adminevents.v1.ServiceChange_Action" json:"action,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version   string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Addr      string                 `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	// Wall-clock timestamp the gateway applied the change.
	TimestampUnixMs int64 `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// Pool replica count after the change (0 when the pool was
	// destroyed entirely).
	ReplicaCount  uint32 `protobuf:"varint,6,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceChange) Reset() {
	*x = ServiceChange{}
	mi := &file_gw_proto_adminevents_v1_adminevents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChange) ProtoMessage() {}

func (x *ServiceChange) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_adminevents_v1_adminevents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChange.ProtoReflect.Descriptor instead.
func (*ServiceChange) Descriptor() ([]byte, []int) {
	return file_gw_proto_adminevents_v1_adminevents_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceChange) GetAction() ServiceChange_Action {
	if x != nil {
		return x.Action
	}
	return ServiceChange_ACTION_UNSPECIFIED
}

func (x *ServiceChange) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceChange) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceChange) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServiceChange) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ServiceChange) GetReplicaCount() uint32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

var File_gw_proto_adminevents_v1_adminevents_proto protoreflect.FileDescriptor

const file_gw_proto_adminevents_v1_adminevents_proto_rawDesc = "" +
	"\n" +
	")gw/proto/adminevents/v1/adminevents.proto\x12\x16gateway.adminevents.v1\"4\n" +
	"\x14WatchServicesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\xc4\x02\n" +
	"\rServiceChange\x12D\n" +
	"\x06action\x18\x01 \x01(\x0e2,.gateway.adminevents.v1.ServiceChange.ActionR\x06action\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04addr\x18\x04 \x01(\tR\x04addr\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\x12#\n" +
	"\rreplica_count\x18\x06 \x01(\rR\freplicaCount\"P\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_REGISTERED\x10\x01\x12\x17\n" +
	"\x13ACTION_DEREGISTERED\x10\x022u\n" +
	"\vAdminEvents\x12f\n" +
	"\rWatchServices\x12,.gateway.adminevents.v1.WatchServicesRequest\x1a%.gateway.adminevents.v1.ServiceChange0\x01BCZAgithub.com/iodesystems/gwag/gw/proto/adminevents/v1;admineventsv1b\x06proto3"

var (
	file_gw_proto_adminevents_v1_adminevents_proto_rawDescOnce sync.Once
	file_gw_proto_adminevents_v1_adminevents_proto_rawDescData []byte
)

func file_gw_proto_adminevents_v1_adminevents_proto_rawDescGZIP() []byte {
	file_gw_proto_adminevents_v1_adminevents_proto_rawDescOnce.Do(func() {
		file_gw_proto_adminevents_v1_adminevents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_proto_adminevents_v1_adminevents_proto_rawDesc), len(file_gw_proto_adminevents_v1_adminevents_proto_rawDesc)))
	})
	return file_gw_proto_adminevents_v1_adminevents_proto_rawDescData
}

var file_gw_proto_adminevents_v1_adminevents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gw_proto_adminevents_v1_adminevents_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gw_proto_adminevents_v1_adminevents_proto_goTypes = []any{
	(ServiceChange_Action)(0),    // 0: gateway.adminevents.v1.ServiceChange.Action
	(*WatchServicesRequest)(nil), // 1: gateway.adminevents.v1.WatchServicesRequest
	(*ServiceChange)(nil),        // 2: gateway.adminevents.v1.ServiceChange
}
var file_gw_proto_adminevents_v1_adminevents_proto_depIdxs = []int32{
	0, // 0: gateway.adminevents.v1.ServiceChange.action:type_name -> gateway.adminevents.v1.ServiceChange.Action
	1, // 1: gateway.adminevents.v1.AdminEvents.WatchServices:input_type -> gateway.adminevents.v1.WatchServicesRequest
	2, // 2: gateway.adminevents.v1.AdminEvents.WatchServices:output_type -> gateway.adminevents.v1.ServiceChange
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gw_proto_adminevents_v1_adminevents_proto_init() }
func file_gw_proto_adminevents_v1_adminevents_proto_init() {
	if File_gw_proto_adminevents_v1_adminevents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_proto_adminevents_v1_adminevents_proto_rawDesc), len(file_gw_proto_adminevents_v1_adminevents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_adminevents_v1_adminevents_proto_goTypes,
		DependencyIndexes: file_gw_proto_adminevents_v1_adminevents_proto_depIdxs,
		EnumInfos:         file_gw_proto_adminevents_v1_adminevents_proto_enumTypes,
		MessageInfos:      file_gw_proto_adminevents_v1_adminevents_proto_msgTypes,
	}.Build()
	File_gw_proto_adminevents_v1_adminevents_proto = out.File
	file_gw_proto_adminevents_v1_adminevents_proto_goTypes = nil
	file_gw_proto_adminevents_v1_adminevents_proto_depIdxs = nil
}
