// Command gnat-ws-relay is the gateway-free live-subscription relay: it serves
// the multiplex WebSocket fan-out over NATS, and spits out the typed TS client.
//
//	gnat-ws-relay serve --nats nats://host:4222 --key SECRET [--addr :8080] [--path /ws]
//	gnat-ws-relay gen runtime <outdir>   # emit the static TS runtime
//
// Typed event payloads come from the adopter's Go event structs, so they're
// generated by calling relay.GenClient(channels, enums, outDir) from the
// adopter's build (go:generate) — the binary alone emits only the runtime.
package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/nats-io/nats.go"

	"github.com/iodesystems/gwag/gw/relay"
)

func main() {
	if len(os.Args) >= 2 {
		switch os.Args[1] {
		case "serve":
			os.Exit(serveCmd(os.Args[2:]))
		case "gen":
			os.Exit(genCmd(os.Args[2:]))
		}
	}
	fmt.Fprintln(os.Stderr, "usage: gnat-ws-relay <serve|gen> ...")
	os.Exit(2)
}

func serveCmd(args []string) int {
	fs := flag.NewFlagSet("serve", flag.ExitOnError)
	natsURL := fs.String("nats", nats.DefaultURL, "NATS URL")
	addr := fs.String("addr", ":8080", "listen address")
	path := fs.String("path", "/ws", "WebSocket mount path")
	key := fs.String("key", "", "HMAC secret for cap verification (or env GNAT_KEY)")
	creds := fs.String("nats-creds", "", "NATS credentials file (subscribe-scoped)")
	_ = fs.Parse(args)

	secret := *key
	if secret == "" {
		secret = os.Getenv("GNAT_KEY")
	}
	if secret == "" {
		fmt.Fprintln(os.Stderr, "gnat-ws-relay: --key (or GNAT_KEY) is required")
		return 2
	}

	var opts []nats.Option
	if *creds != "" {
		opts = append(opts, nats.UserCredentials(*creds))
	}
	nc, err := nats.Connect(*natsURL, opts...)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gnat-ws-relay: nats connect:", err)
		return 1
	}
	defer func() { _ = nc.Drain() }()

	r := relay.New([]byte(secret), relay.NatsSource(nc))
	mux := http.NewServeMux()
	mux.Handle(*path, r.Handler())
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })

	srv := &http.Server{Addr: *addr, Handler: mux}
	go func() {
		sig := make(chan os.Signal, 1)
		signal.Notify(sig, os.Interrupt, syscall.SIGTERM)
		<-sig
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = srv.Shutdown(ctx)
	}()

	fmt.Fprintf(os.Stderr, "gnat-ws-relay: serving %s%s, bus %s\n", *addr, *path, *natsURL)
	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		fmt.Fprintln(os.Stderr, "gnat-ws-relay:", err)
		return 1
	}
	return 0
}

func genCmd(args []string) int {
	if len(args) >= 2 && args[0] == "runtime" {
		out := args[1]
		if err := relay.WriteRuntime(out); err != nil {
			fmt.Fprintln(os.Stderr, "gnat-ws-relay:", err)
			return 1
		}
		fmt.Println("wrote", filepath.Join(out, relay.RuntimeFile))
		return 0
	}
	fmt.Fprintln(os.Stderr, "usage: gnat-ws-relay gen runtime <outdir>")
	fmt.Fprintln(os.Stderr, "  (typed payloads: call relay.GenClient(channels, enums, outDir) from your build)")
	return 2
}
