// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: adminauth/v1/adminauth.proto

package adminauthv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminAuthorizer_Authorize_FullMethodName = "/gateway.adminauth.v1.AdminAuthorizer/Authorize"
)

// AdminAuthorizerClient is the client API for AdminAuthorizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminAuthorizer is the optional delegate the gateway calls before
// AdminMiddleware accepts a write to /admin/*. Implement it in your
// authz service and register it under namespace "_admin_auth" /
// version v1.
//
// Policy: if a delegate is registered, the gateway consults it on
// every protected request. OK accepts, DENIED rejects (without
// falling through). Anything else (UNAVAILABLE, NOT_CONFIGURED,
// UNSPECIFIED, transport error) falls through to boot-token bearer
// verification — the always-works emergency hatch is non-negotiable.
type AdminAuthorizerClient interface {
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
}

type adminAuthorizerClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminAuthorizerClient(cc grpc.ClientConnInterface) AdminAuthorizerClient {
	return &adminAuthorizerClient{cc}
}

func (c *adminAuthorizerClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, AdminAuthorizer_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminAuthorizerServer is the server API for AdminAuthorizer service.
// All implementations must embed UnimplementedAdminAuthorizerServer
// for forward compatibility.
//
// AdminAuthorizer is the optional delegate the gateway calls before
// AdminMiddleware accepts a write to /admin/*. Implement it in your
// authz service and register it under namespace "_admin_auth" /
// version v1.
//
// Policy: if a delegate is registered, the gateway consults it on
// every protected request. OK accepts, DENIED rejects (without
// falling through). Anything else (UNAVAILABLE, NOT_CONFIGURED,
// UNSPECIFIED, transport error) falls through to boot-token bearer
// verification — the always-works emergency hatch is non-negotiable.
type AdminAuthorizerServer interface {
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	mustEmbedUnimplementedAdminAuthorizerServer()
}

// UnimplementedAdminAuthorizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminAuthorizerServer struct{}

func (UnimplementedAdminAuthorizerServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedAdminAuthorizerServer) mustEmbedUnimplementedAdminAuthorizerServer() {}
func (UnimplementedAdminAuthorizerServer) testEmbeddedByValue()                         {}

// UnsafeAdminAuthorizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminAuthorizerServer will
// result in compilation errors.
type UnsafeAdminAuthorizerServer interface {
	mustEmbedUnimplementedAdminAuthorizerServer()
}

func RegisterAdminAuthorizerServer(s grpc.ServiceRegistrar, srv AdminAuthorizerServer) {
	// If the following call panics, it indicates UnimplementedAdminAuthorizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminAuthorizer_ServiceDesc, srv)
}

func _AdminAuthorizer_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthorizerServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthorizer_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthorizerServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminAuthorizer_ServiceDesc is the grpc.ServiceDesc for AdminAuthorizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminAuthorizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.adminauth.v1.AdminAuthorizer",
	HandlerType: (*AdminAuthorizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _AdminAuthorizer_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adminauth/v1/adminauth.proto",
}
