// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: adminauth/v1/adminauth.proto

package adminauthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminAuthCode int32

const (
	AdminAuthCode_ADMIN_AUTH_CODE_UNSPECIFIED AdminAuthCode = 0
	// Delegate authorized the request. The middleware accepts without
	// checking the boot token.
	AdminAuthCode_ADMIN_AUTH_CODE_OK AdminAuthCode = 1
	// Delegate explicitly rejected. The middleware returns 401 without
	// falling through to the boot token.
	AdminAuthCode_ADMIN_AUTH_CODE_DENIED AdminAuthCode = 2
	// Delegate is currently unavailable (degraded backend, exceeded
	// budget, etc.). Middleware falls through to boot-token check.
	AdminAuthCode_ADMIN_AUTH_CODE_UNAVAILABLE AdminAuthCode = 3
	// Delegate is registered but unwilling to make a decision (e.g.
	// policy not loaded). Middleware falls through to boot-token.
	AdminAuthCode_ADMIN_AUTH_CODE_NOT_CONFIGURED AdminAuthCode = 4
)

// Enum value maps for AdminAuthCode.
var (
	AdminAuthCode_name = map[int32]string{
		0: "ADMIN_AUTH_CODE_UNSPECIFIED",
		1: "ADMIN_AUTH_CODE_OK",
		2: "ADMIN_AUTH_CODE_DENIED",
		3: "ADMIN_AUTH_CODE_UNAVAILABLE",
		4: "ADMIN_AUTH_CODE_NOT_CONFIGURED",
	}
	AdminAuthCode_value = map[string]int32{
		"ADMIN_AUTH_CODE_UNSPECIFIED":    0,
		"ADMIN_AUTH_CODE_OK":             1,
		"ADMIN_AUTH_CODE_DENIED":         2,
		"ADMIN_AUTH_CODE_UNAVAILABLE":    3,
		"ADMIN_AUTH_CODE_NOT_CONFIGURED": 4,
	}
)

func (x AdminAuthCode) Enum() *AdminAuthCode {
	p := new(AdminAuthCode)
	*p = x
	return p
}

func (x AdminAuthCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminAuthCode) Descriptor() protoreflect.EnumDescriptor {
	return file_adminauth_v1_adminauth_proto_enumTypes[0].Descriptor()
}

func (AdminAuthCode) Type() protoreflect.EnumType {
	return &file_adminauth_v1_adminauth_proto_enumTypes[0]
}

func (x AdminAuthCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminAuthCode.Descriptor instead.
func (AdminAuthCode) EnumDescriptor() ([]byte, []int) {
	return file_adminauth_v1_adminauth_proto_rawDescGZIP(), []int{0}
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Bearer token presented by the client (the raw value after
	// `Bearer `). Empty string when the request had no Authorization
	// header — the delegate decides whether to accept anonymous calls.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// HTTP method, uppercased (POST/PUT/PATCH/DELETE/...).
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Request path on the gateway (e.g. "/admin/peers/X/forget").
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Inbound remote address (best-effort; may be empty if the gateway
	// is behind a proxy that doesn't forward it).
	RemoteAddr string `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminauth_v1_adminauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminauth_v1_adminauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_adminauth_v1_adminauth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthorizeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthorizeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuthorizeRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code AdminAuthCode `protobuf:"varint,1,opt,name=code,proto3,enum=gateway.adminauth.v1.AdminAuthCode" json:"code,omitempty"`
	// Optional, for operator logs. Never leaked to clients.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminauth_v1_adminauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminauth_v1_adminauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_adminauth_v1_adminauth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetCode() AdminAuthCode {
	if x != nil {
		return x.Code
	}
	return AdminAuthCode_ADMIN_AUTH_CODE_UNSPECIFIED
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_adminauth_v1_adminauth_proto protoreflect.FileDescriptor

var file_adminauth_v1_adminauth_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x22, 0x75, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22, 0x64, 0x0a, 0x11, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x37, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x2a, 0xa9, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x41, 0x55, 0x54,
	0x48, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x41, 0x55,
	0x54, 0x48, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16,
	0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f,
	0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x41, 0x44, 0x4d, 0x49,
	0x4e, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x41, 0x56,
	0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x22, 0x0a, 0x1e, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x55, 0x52, 0x45, 0x44, 0x10, 0x04, 0x32, 0x6f, 0x0a,
	0x0f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72,
	0x12, 0x5c, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x12, 0x26, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40,
	0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6f, 0x64,
	0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2d,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75, 0x74,
	0x68, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adminauth_v1_adminauth_proto_rawDescOnce sync.Once
	file_adminauth_v1_adminauth_proto_rawDescData = file_adminauth_v1_adminauth_proto_rawDesc
)

func file_adminauth_v1_adminauth_proto_rawDescGZIP() []byte {
	file_adminauth_v1_adminauth_proto_rawDescOnce.Do(func() {
		file_adminauth_v1_adminauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_adminauth_v1_adminauth_proto_rawDescData)
	})
	return file_adminauth_v1_adminauth_proto_rawDescData
}

var file_adminauth_v1_adminauth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_adminauth_v1_adminauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adminauth_v1_adminauth_proto_goTypes = []interface{}{
	(AdminAuthCode)(0),        // 0: gateway.adminauth.v1.AdminAuthCode
	(*AuthorizeRequest)(nil),  // 1: gateway.adminauth.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 2: gateway.adminauth.v1.AuthorizeResponse
}
var file_adminauth_v1_adminauth_proto_depIdxs = []int32{
	0, // 0: gateway.adminauth.v1.AuthorizeResponse.code:type_name -> gateway.adminauth.v1.AdminAuthCode
	1, // 1: gateway.adminauth.v1.AdminAuthorizer.Authorize:input_type -> gateway.adminauth.v1.AuthorizeRequest
	2, // 2: gateway.adminauth.v1.AdminAuthorizer.Authorize:output_type -> gateway.adminauth.v1.AuthorizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_adminauth_v1_adminauth_proto_init() }
func file_adminauth_v1_adminauth_proto_init() {
	if File_adminauth_v1_adminauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adminauth_v1_adminauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminauth_v1_adminauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adminauth_v1_adminauth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adminauth_v1_adminauth_proto_goTypes,
		DependencyIndexes: file_adminauth_v1_adminauth_proto_depIdxs,
		EnumInfos:         file_adminauth_v1_adminauth_proto_enumTypes,
		MessageInfos:      file_adminauth_v1_adminauth_proto_msgTypes,
	}.Build()
	File_adminauth_v1_adminauth_proto = out.File
	file_adminauth_v1_adminauth_proto_rawDesc = nil
	file_adminauth_v1_adminauth_proto_goTypes = nil
	file_adminauth_v1_adminauth_proto_depIdxs = nil
}
